- src/hidpp10.c
- src/hidpp10.h
Not doing anything useful with them yet but this documents 3 of the unknown bytes.
We also skipped one too many profiles.
> Read colors from profiles in hidpp10

- src/libratbag.c
Seen on the second input node of the Roccat Kone XTD:
"ratbag error: ROCCAT Kone XTD: driver specified in hwdb not found: roccat
With the new hwdb matching, we should not try any other driver not having
the right id, so simplify the for loop to find the driver only.
Fixes #32
Signed-off-by: Benjamin Tissoires <benjamin.tissoires@gmail.com>
> prevent error to be shouted when the .probe() returns -ENODEV

- src/driver-hidpp10.c
- src/hidpp10.c
- src/hidpp10.h
- tools/hidpp10-dump-page.c
I am 99% sure I did not break things here.
Can somebody test the last 1%?
Re-pull request, was missing one staged changed in my tree which made the build fail.
> hidpp10: rename hidpp10_device_new_from_idx into hidpp10_device_new

- src/hidpp10.c
- src/hidpp10.h
- src/libratbag.c
Follow up patches for #56 and removal of an unused variable.
> Follow up for #56

- src/hidpp10.c
On the G9 the response to a 0x63 is a short report. The G9 does
not have individual resolutions for X and Y and thus only needs
to report a single value.
The set version of 0x63 should probably also be updated. However,
while my testing of such a change worked better than with long
reports there are still strange side effects of setting resolution,
like turning off all the LED's. LGS also seems to do a full profile
read/write instead of using 0x63 when changing the resolution.
> hidpp10: Fix getting current resolution on G9

- data/logitech-g500s.svg
Changed button labels with their proper numbers and rotated arrows for wheel tilt buttons.
> data: Fix G500s button labels and arrows

- src/libratbag.c
- src/libratbag.h
- src/libratbag.sym
- test/test-context.c
- tools/shared.c
This is on top of pull #72, so better to pull this one here directly instead of the other and it'll be autoclosed rather than messing up the branch with the useless merge commits.
> Use error enums

- src/driver-etekcity.c
- src/driver-hidpp10.c
- src/driver-hidpp20.c
- src/driver-roccat.c
- src/libratbag-hidraw.c
- src/libratbag.c
Fixes #78 and another error message I get a lot with my half-busted roccat kone
> Fix a couple of error messages

- hwdb/70-libratbag-mouse.hwdb
Signed-off-by: Marty Plummer <ntzrmtthihu777@gmail.com>
> Added hwdb entry for G602 (046d:c537)

- src/driver-gskill.c
- src/libratbag-private.h
- src/libratbag.c
- src/libratbag.h
- src/libratbag.sym
- tools/ratbag-command.c
Pull request for introducing the new profile-oriented API in libratbag. More info in commit descriptions.
> New profile-oriented API

- release.sh
Copied from Xorg/util/modular, the license should not be an issue
here.
Signed-off-by: Benjamin Tissoires <benjamin.tissoires@gmail.com>
> Add a release script to generate the announce email

- src/driver-gskill.c
- src/libratbag-util.c
- test/Makefile.am
- test/test-iconv-helper.c
Realized that the code I had written for gskill to make sure there was always a profile name wasn't working like I had thought it was… traced down the issue to being that the iconv helper was not working anywhere as well as I thought it was and figured in addition to fixing that it would be a good idea to write some basic tests to make sure it doesn't break in the future.
> Important iconv fixes + test

- src/driver-etekcity.c
- src/driver-gskill.c
- src/driver-hidpp10.c
- src/driver-hidpp20.c
- src/driver-logitech-g300.c
- src/driver-roccat.c
- src/driver-test.c
- src/hidpp10.h
- src/libratbag-private.h
- src/libratbag-test.h
- src/libratbag.c
- src/libratbag.h
- src/libratbag.sym
- test/test-device.c
> libratbag api support LEDs

- src/hidpp-generic.c
- src/hidpp-generic.h
- src/hidpp20.c
- src/hidpp20.h
- src/libratbag.h
> hidpp20: Implement feature 0x8070: LED effects

- src/driver-test.c
- src/libratbag-private.h
- src/libratbag-test.h
- src/libratbag.c
- src/libratbag.h
- src/libratbag.sym
- test/test-device.c
> Add the ability to set LED effects

- data/logitech-g300.svg
Logitech g300 svg data. I don't have this mouse so not 100% sure about mappings.
> add logitech g300 svg data

- data/logitech-g900.svg
- hwdb/70-libratbag-mouse.hwdb
SVG data for Logitech G900 mouse, with button on underside documented.
> SVG Logitech G900 Data

- src/driver-hidpp20.c
can get LED's current settings from profile.
stores LED's mode, color, and effect settings to profile
> G900, g502 Modify LEDs settings

- doc/Makefile.am
- doc/libratbag.doxygen.in
- tools/Makefile.am
- tools/hidpp10-dump-page.c
- tools/hidpp20-dump-page.c
- tools/ratbag-command.c
- tools/shared.c
All these were things shown by the wip meson conversion
> build system cleanups

- src/driver-hidpp20.c
I do not like duplicating ratbag_old_write_profile() into each driver, but, heh.
This allows to have only one write to the device instead of 8, so it's always nice.
Tested on the MX master for non profile mice, and the G900.
> hidpp20drv: switch to the commit API

- src/hidpp10.c
Still sending out the PR, even if I am not able to test it right now.
Either somebody with an affected hardware checks this, or we wait next week for me to test it.
> hidpp10: fix coverity issue

- DBusInterface.md
- ratbagd/ratbagd-resolution.c
https://github.com/libratbag/libratbag/issues/180
This is the ratbagd part of it.
> resolution: add support for min/max resolutions

- DBusInterface.md
- ratbagd/ratbagd-device.c
> RatbagdDevice: add commit method

- dbus/org.freedesktop.ratbag_devel1.conf.in
- meson.build
- ratbagd/ratbagd-button.c
- ratbagd/ratbagd-device.c
- ratbagd/ratbagd-led.c
- ratbagd/ratbagd-profile.c
- ratbagd/ratbagd-resolution.c
- ratbagd/ratbagd.c
- ratbagd/ratbagd.h
- tools/ratbag-git-sha.sh
- tools/ratbagctl.devel.in
- tools/ratbagctl.in
Update ratbagctl ratbagd binding by copying the file from piper (do we have license issues doing that?).
Add a new tool run_ratbagctl which allows developers to spawn ratbagd and use the ratbagd from master insterad of the system wide one.
> run ratbagctl on master through run_ratbagctl

- ratbagd/ratbagd-led.c
- ratbagd/ratbagd-resolution.c
Related to https://github.com/libratbag/piper/pull/35
> ratbagd: send property changed signals when we change the properties

- ratbagd/ratbagd-resolution.c
Instead of copying them into our own struct, just query libratbag when we need
them. This brings the resolution code in line with the button and LED code
which don't do caching either.
Eventually we may want to cache them again to detect changes behind your
back (if libratbag value != our cached value) but for now this reduces the
work ratbagd does.
> ratbagd: drop caching of libratbag variables

- data/gnome/README.md
As discussed in https://github.com/libratbag/piper/issues/48
> data/gnome/README: include note on z-ordering

- data/gnome/logitech-g700.svg
See https://github.com/libratbag/piper/issues/48
> data/gnome/logitech-g700: fix overlapping paths

- tools/ratbagctl.in
- tools/ratbagctl.test.in
Going from 20 seconds to 2 is always good
> ratbagctl tests speedup

- meson.build
Otherwise we won't notice changes to it
> meson: add ratbagd.py as input source for merge_ratbagd.py

- circle.yml
- meson.build
- ratbagd/ratbagd.c
- src/libratbag.c
- test/test-context.c
- test/test-device.c
- test/test-iconv-helper.c
- tools/ratbagctl.test.in
- tools/ratbagctl.test.wrapper
- tools/ratbagd.py
Hook up ratbagctl.test to the test suite and make sure it passes both normal and valgrind runs
> Test suite cleanups

- DBusInterface.md
- ratbagd/ratbagd-resolution.c
- src/libratbag.c
- tools/ratbagctl.in
- tools/ratbagctl.test.in
- tools/ratbagd.py
Fixes #80
Though it's only in ratbagd/ratbagctl, we need some work in the drivers (but I like to remove the skipped tests)
> implement resolution active set

- DBusInterface.md
- ratbagd/ratbagd-button.c
- ratbagd/ratbagd-led.c
- ratbagd/ratbagd.c
- tools/ratbagctl.in
- tools/ratbagctl.test.in
- tools/ratbagd.py
This fixes #252 and also makes the LED type return an enum value.
> Enumify the remaining string properties in ratbagd

- tools/ratbagctl.in
> ratbagctl fixes

- src/driver-hidpp20.c
- src/hidpp20.c
- src/hidpp20.h
- tools/ratbag-command.c
Fix HID++ 2.0 with resolution active
> hidpp20: fix resolution active set/get

- data/gnome/logitech-g900.svg
- meson.build
Related issues: #300, #213.
@kudlatyamroth or @kaymio please test this.
> Add Logitech G900 SVG for gnome theme

- tools/ratbagd.py
This concerns the changes made in https://github.com/libratbag/piper/pull/168, and shouldn't be merged when we close the other one to keep things in sync.
> Sync ratbagd.py with Piper, part 2

- meson.build
- src/libratbag-data.c
- tools/ratbagctl.devel.in
And set it for the tests, so we can test with in-tree files.
> Get the libratbag data dir from the environment variable

- src/driver-hidpp20.c
Valgrind complains about it, so let's fix it.
> hidpp20: fix mem leak

- src/driver-logitech-g300.c
Piper is warning that no active resolution is set. This fixes that. We can read the active profile and resolution from report 0xF0.
For the active profile we read the active resolution
from the mouse during probe.
When changing the active profile we set the default
resolution to active.
> G300: set active resolution

- tools/ratbagctl.in
- tools/ratbagctl.test.in
OK, this time it is better (I think).
So now, we should be better at checking if the ratbagd process has been started or not.
> tools: few ratbagctl fixes

- src/driver-hidpp10.c
- src/driver-test.c
- src/libratbag-private.h
Some cleanups I found while working on the flat probe() bits
> Misc cleanups

- src/driver-etekcity.c
- src/driver-gskill.c
- src/driver-hidpp10.c
- src/driver-hidpp20.c
- src/driver-logitech-g300.c
- src/driver-roccat.c
- src/driver-test.c
- src/libratbag-private.h
- src/libratbag.c
> Switch to a flat probe() function instead of the callbacks

- tools/ratbagctl.1
Should be closer to the truth now.
> Update ratbagctl man

- src/driver-etekcity.c
- src/driver-hidpp20.c
- src/driver-logitech-g300.c
- src/driver-roccat.c
- src/libratbag-private.h
- src/libratbag.c
While trying to work on the macro writing support, I realized the way macros were freed were not correct, so we need to take care of our leaks better :)
Also the last patch is just a carry over I realized that it wouldn't hurt to have.
> Some macro related memleak fixes

- src/driver-hidpp20.c
- src/hidpp20.c
- src/hidpp20.h
Grab the capabilities from the device where possible instead of just assuming we have them.
I'm not 100% sure I read the monochrome-only effects bit right, @SonicFrog please confirm that bit, thanks.
> hidpp20 led capabilities

- src/driver-steelseries.c
Small incremental improvements to to the steelseries driver.
Sets the report rate list and initializes the buttons to their defaults.
> Steelseries small improvements

- src/driver-steelseries.c
To specify the colors to cycle trough we write a list of
colors and their individual share of the total cycle duration.
Solid colors only have a single color in their list.
Breathing mode will cycle to and from the picked color and black.
Cycle mode will cycle through red, green, and blue.
> steelseries: support cycle and breathing LED mode

- data/devices/steelseries-sensei-310.device
- data/gnome/steelseries-sensei310.svg
- meson.build
- src/driver-steelseries.c
This adds support for the SteelSeries Sensei 310. The mouse is very close to the Rival 310, but has two additional buttons and different default button mappings.
> SteelSeries sensei 310

- data/devices/steelseries-rival.device
- data/gnome/steelseries-rival.svg
- src/driver-steelseries.c
Initial support for the original Rival mouse.
Setting resolutions, report rate and LED color and
modes.
No key mappings yet, and breathing duration is fixed.
> steelseries: support the original Rival

- src/driver-steelseries.c
- src/libratbag-private.h
- src/libratbag.c
Solves https://github.com/libratbag/libratbag/issues/436
I was only able to check in my Steelsereis Rival 310. Please test on other mice.
> Add dirty flag in resolution

- src/libratbag-util.c
- src/libratbag-util.h
Required for https://github.com/libratbag/libratbag/pull/472
> libratbag: fix order when inserting new element in list

- src/driver-steelseries.c
This should make the code easier to be maintained.
> Implement a structure for cycle

- doc/dbus.rst
- ratbagd/ratbagd-device.c
- tools/ratbagctl.in
- tools/ratbagd.py
This is on top of #522 
Fixes #521 and is the foundation for https://github.com/libratbag/piper/issues/245
This is an API break so we'll need to push a release out and then we can update piper to rely on that release.
> Pass SVGs as fds

- tools/ratbagc.py.in
Showed up in #526
https://github.com/libratbag/libratbag/issues/526#issuecomment-420016451
> tools: handle NULL svgs in ratbag-command

- data/gnome/logitech-g600.svg
> data: fix Logitech g600 button 6/7 assignment

- circle.yml
- meson.build
It's too easy to forget to add the file to the meson.build file, so let's add a check for that in the CI.
> Check that all our svg and device files are installed

- src/driver-hidpp20.c
Since a0830a8aaaa5168f4a2bb1c0d7594de50fcb9fb0, we can re-add the simple keybindings capabilities. It's time the HID++ 2.0 devices get this.
This used to be working with the KEY API, but this has been dropped in favor of the macro one.
This effectively replaces #402
> hidpp20: use macros for key+modifiers

- data/gnome/logitech-g-pro-wireless.svg
We don't want this for copyright reasons.
> data/gnome/logitech-g-pro-wireless: don't use Logitech LED logo

- data/gnome/logitech-g603.svg
- meson.build
Added a proper SVG for the Logitech G603 as requested in https://github.com/libratbag/libratbag/pull/505
Sorry if this was submitted improperly, I'm still pretty new to using git.
> data: added Logitech G603 svg

- data/devices/logitech-g603.device
- data/devices/logitech-g900-wireless.device
- meson.build
Cherrypicked device file from #505 
Closes #505
> data: add device file for Logitech G603

- tools/ratbagc.py.in
Regression introduced in 107a649e08eee2e90917ddf06082bce8a723d5ae
> ratbag-command: fix get_svg_fd()

- tools/ratbagctl.in
- tools/ratbagctl.test.in
See #635 for a full description, or the commit message
> ratbagctl: put the device node at the beginning of the command

- doc/dbus.rst
- ratbagd/ratbagd-device.c
- ratbagd/ratbagd-test.c
- ratbagd/ratbagd.c
- ratbagd/ratbagd.h
- tools/ratbagctl.in
- tools/ratbagctl.test.in
- tools/ratbagd.py
See #641 for a longer explanation.
Fixes #641
> Move the device ID generation to ratbagctl

- circle.yml
- meson.build
- src/libratbag-data.c
Now that the SVGs are gone, we don't need the subfolder anymore
> Install the device files in the top-level datadir

- data/devices/logitech-g100s.device
- meson.build
> data: add Logitech G100s

- data/devices/logitech-g100s.device
- meson.build
This reverts commit 0e28d82a16a39339efb15fbc4c14ca3ca60be9de.
Solves #672 
Re-reading the message history I realize that the actual mouse functions weren't actually tested, my bad :persevere:.
> revert "data: add Logitech G100s (#670)"

- ratbagd/ratbagd-button.c
- tools/ratbagd.py
Don't send property updates for props that don't exist anymore.
> ratbagd: fix property update notifications

- data/devices/data-parse-test.py
- doc/conf.py.in
- tools/merge_ratbagd.py
The only notable one here is the regex that had an escape sequence
> Fix flake8 warnings

- tools/ratbagc.py.in
- tools/ratbagctl.in
- tools/ratbagd.py
Because this is 2019 and even python has enums now (for half a decade or so already)
> Use proper enums in ratbagd.py

- circle.yml
- meson.build
- ratbagd/ratbagd-profile.c
@YoyPa does this one work for your crazy profile names? In theory it should, but... well... :)
> ratbagd: use libunistring to convert profile names to utf-8

- src/driver-steelseries.c
Fixes #683
@danielfpferreira can you confirm this solves your issue?
> steelseries: fix regression in v2 led

- data/devices/logitech-g403.device
- data/devices/logitech-g900.device
kernel v5.2 should solve #380, finally
Fixes #380
> data: update G900 and G403 for kernel v5.2+

- src/driver-hidpp20.c
- tools/ratbagc.py.in
- tools/ratbagctl.in
- tools/ratbagd.py
I pulled out my G502 and found a few issues today.
I think it might solve #692 but I am not entirely sure if this is everything that needs to be done.
Anyway, feedback welcome :)
> G502 fixes (more likely HID++ 2.0)

- data/devices/logitech-MX-Master.device
> data: add other ID to MX Master

- src/driver-hidpp20.c
> logitech: don't show hidden features

- data/devices/logitech-MX518.device
- meson.build
> data: add Logitech MX518

- data/devices/logitech-MX-Ergo.device
> data: add ID to MX Ergo

- data/devices/logitech-Marathon-M705.device
- meson.build
> data: add Logitech Marathon M705

- src/hidpp20.c
This should have been done in #733 but I just noticed it now.
> Simplify profiles initialize

- data/devices/logitech-MX-Vertical.device
- meson.build
> data: add MX Vertical

- src/driver-steelseries.c
- src/hidpp-generic.h
- src/hidpp10.c
- src/hidpp20.c
- src/libratbag-util.h
> hidpp20: fix 0x1001 comments, add missing ASE and use get_unaligned_be_u16

- ratbagd/ratbagd.c
See https://github.com/bus1/dbus-broker/issues/206 for a discussion on why this is needed.
Fixes #753
> Reload DBus config after installing the policy file

- src/hidpp20.c
- src/hidpp20.h
> hidpp20: add new profile layout (0x04)

- src/driver-hidpp20.c
- src/hidpp-generic.c
- src/hidpp-generic.h
- src/hidpp20.c
- src/hidpp20.h
> hidpp20: add support for RGB Effects feature (0x8071)

- circle.yml
> circle CI: add meson plain and release build types

- release.sh
hand-composing stuff is boring, let's re-use the script
> Release script fixes (for piper, mainly)

- src/hidpp10.c
> Switch to profile 0 if our current active profile is the factory profile.

- data/devices/data-parse-test.py
- data/devices/logitech-g305.device
- meson.build
- src/driver-hidpp20.c
- src/hidpp20.c
- src/hidpp20.h
- src/libratbag-data.c
- src/libratbag-data.h
> add quirk system & full support for the G305

- src/driver-hidpp20.c
> hidpp20: fix setting default resolution

- src/hidpp10.c
- src/libratbag.c
> hidpp10: require the current profile feature

- data/devices/logitech-g502-hero-wireless.device
- meson.build
I've tried to follow the guide at:
https://github.com/libratbag/libratbag/wiki/Adding-a-new-device
And tried to add the G502 Hero Wireless device.
> Add Logitech G502 Hero Wireless device

- data/devices/logitech-g602.device
- src/driver-hidpp20.c
- src/hidpp20.c
- src/hidpp20.h
- src/libratbag-data.c
> hidpp20: add suport for the G602

- data/devices/logitech-g604.device
- meson.build
> devices: add Logitech G604

- data/devices/steelseries-kinzu-v3.device
- meson.build
Added support for the SteelSeries Kinzu V3
> data: add Steelseries Kinzu V3

- data/devices/logitech-M585-M590.device
- meson.build
I added Logitech M585/M590 support, please review and merge it :smiley:
> Add Logitech M585/M590 support.

- data/devices/logitech-g513.device
- meson.build
- src/driver-hidpp20.c
> Add support for the Logitech G513

- src/driver-hidpp20.c
- src/hidpp20.c
- src/hidpp20.h
> HID++ 2.0 `0x8060` support

- ratbagd/ratbagd-device.c
- src/driver-hidpp20.c
This could have helped spot #716/#834 much easier.
> Better errors

- src/driver-hidpp20.c
Removes useless setting of the dpi index when updating resolutions.
Removes weird empty line.
> Minor hidpp20 driver work

- data/devices/logitech-g-powerplay.device
- meson.build
> data: add the Logitech G Powerplay

- data/devices/logitech-g402.device
Signed-off-by: simrat39 <simrats169169@gmail.com>
> devices: Set g402 LedTypes

- data/devices/logitech-M720.device
- meson.build
> data: add Logitech M720

- data/devices/data-parse-test.py
- data/devices/logitech-g305.device
- src/driver-hidpp20.c
- src/libratbag-data.c
> Overwrite led count for the G305

- src/hidpp10.c
> hidpp10: fix circular loop on hidpp10_onboard_profiles_read_macro

- src/driver-hidpp10.c
- src/hidpp10.c
- src/hidpp10.h
- src/liblur.c
- tools/hidpp10-dump-page.c
> Fix crash on hidpp10 device initialization failure

- data/devices/logitech-g935.device
- meson.build
> data: add Logitech G935

- src/hidpp20.c
> hidpp20: keep unsupported button mappings

- data/devices/logitech-MX-Vertical.device
Add bluetooth id for logitech mx vertical
> data: add bluetooth ID to the MX Vertical

- data/devices/roccat-kone-pure.device
- src/driver-roccat-kone-pure.c
> Fix Roccat Kone Pure Driver

- data/devices/logitech-g102-g203.device
My G203 has diffrent ID, so I added it to .device file.
> data: add another device ID for G203 mouse

- data/devices/glorious-model-d.device
- data/devices/glorious-model-o.device
- meson.build
- src/driver-sinowealth.c
- src/libratbag-data.c
- src/libratbag-private.h
- src/libratbag.c
RGB color picker doesn't quite work right, I suspect I slipped by a few bytes while writing the C struct based on my notes. Everything else just works as far as I can tell.
Implements #1007
> Add sinowealth driver for Glorious Model O/D

- src/driver-logitech-g300.c
"Fixed" the dpi steps of the g300 to 50 to allow for finer adjustment.
> g300: use the correct step size

- data/devices/logitech-g102-g203.device
> data: add the G203 name to the .device file

- src/driver-sinowealth.c
> sinowealth: silence warning

- data/devices/logitech-MX-Anywhere2.device
> data: add an ID to the MX Anywhere 2

- data/devices/logitech-g915-tkl.device
- meson.build
> data: add G915 TKL

- data/devices/openinput.device
- meson.build
- src/driver-openinput.c
- src/libratbag-data.c
- src/libratbag-private.h
- src/libratbag.c
WIP https://github.com/openinput-fw/openinput/tree/master
cc @perigoso
> Add openinput driver

- data/devices/logitech-M500s.device
- meson.build
Support for Logitech M500s mouse.
I am working on svg for piper but this is not my cup of tea...
> data: add support for Logitech M500s mouse

- data/devices/roccat-kone-pure.device
The last part added is for a variant called "Roccat Kone Pure SEL".
> data: add SEL variant to Roccat Kone Pure

- src/driver-openinput.c
Signed-off-by: Stephen Kitt <steve@sk2.org>
> openinput: fix "Unknown" typo

- ratbagd/ratbagd-profile.c
Fixes #692 and closes #1126. Also unblocks https://github.com/libratbag/piper/pull/494.
> ratbagd-profile: modify report rate change sanity check 

- data/devices/logitech-Performance-Mouse-MX.device
- meson.build
Add support for this old business Logitech mouse.
Hint: I'm new to libratbag, so sorry if there is something missing.
> data: Add (old) Logitech Performance Mouse MX

- data/devices/logitech-g733.device
- meson.build
Led works! I can change colors, mode, duration and brightness. 
Buttons dont work, always point to UNKNOW as see above:
```
screaming-acouchy - Logitech G733 Gaming Headset
Model: usb:046d:0ab5:0
Number of Buttons: 8
Number of Leds: 2
Number of Profiles: 1
Profile 0: (active)
Name: n/a
Button: 0 is mapped to UNKNOWN
Button: 1 is mapped to UNKNOWN
Button: 2 is mapped to UNKNOWN
Button: 3 is mapped to UNKNOWN
Button: 4 is mapped to UNKNOWN
Button: 5 is mapped to UNKNOWN
Button: 6 is mapped to UNKNOWN
Button: 7 is mapped to UNKNOWN
LED: 0, depth: rgb, mode: cycle, duration: 5000, brightness: 0
LED: 1, depth: rgb, mode: cycle, duration: 10000, brightness: 0
```
Number of buttons is wrong. The device only have 2 buttons and a volume scroll. 
As mentioned in #1021, the output of hid-recorder …
> Add support to Logitech G733

- src/driver-steelseries.c
Set 0x00 report_id for every steelseries device, similar to `rivalcfg project`
fixes #804
> steelseries: set report_id of 0x00 

- README.md
This is straight forward, but lets not assume people know about it. #1033
> README: add uninstall instruction

- .github/workflows/main.yml
Different variable names and no-one noticed.
This means we need to add a few dependencies that weren't needed before.
> CI: actually test with the various meson args

- tools/ratbagc.py.in
Extracted from #1250 so we don't need to wait until the driver is ready
cc @kyokenn
> fix ratbag-command led setting

- src/driver-sinowealth.c
I had to move some stuff around to not read data from the mouse twice.
> sinowealth: detect LED count at run-time

- src/libratbag-data.c
Found by valgrind. I also feel that there is another memory leak of the
same nature a bit higher in `init_data_hidpp10`.
Introduced by me. :^)
> steelseries: fix a memory leak

- src/driver-sinowealth.c
> sinowealth: add support for button action changing

- src/hidpp20.c
I tested this patch on G502 and G900.
> hidpp20: fix set onboard mode

- data/devices/asus-rog-buzzard.device
- data/devices/asus-rog-chakram.device
- data/devices/asus-rog-gladius2-origin-pink.device
- data/devices/asus-rog-gladius2-origin.device
- data/devices/asus-rog-gladius2.device
- data/devices/asus-rog-keris-wireless.device
- data/devices/asus-rog-pugio.device
- data/devices/asus-rog-strix-carry.device
- data/devices/asus-rog-strix-impact.device
- data/devices/asus-rog-strix-impact2-wireless.device
- data/devices/device.example
- meson.build
- src/asus.c
- src/asus.h
- src/driver-asus.c
- src/libratbag-data.c
- src/libratbag-data.h
- src/libratbag-private.h
- src/libratbag.c
Fixes https://github.com/libratbag/libratbag/issues/632 ("Asus ROG Gladius II" part)
Fixes https://github.com/libratbag/libratbag/issues/925 (some mice may needed .device files, the protocol is almost the same between them)
> Add ASUS driver and fix ratbag-command led setting

- .github/workflows/main.yml
- .github/workflows/pages.yml
> CI: update runners to use Node 16

- data/devices/asus-rog-strix-impact2.device
fixes https://github.com/libratbag/libratbag/issues/1370
> asus: add strix impact 2

- data/devices/logitech-g303-shroud.device
Adds basic support for Logitech G303 Shroud Edition
> Logitech G303 Shroud Edition device file

- data/devices/steelseries-kinzu-v3.device
> Adjust offered resolutions for SteelSeries Kinzu V3

- meson.build
> build: bump ratbagd DBus API version

- data/devices/logitech-MX-Anywhere3B.device
- meson.build
- test/data-parse-test.py
> Fix data tests

- doc/dbus.rst
- ratbagd/ratbagd-json.c
- ratbagd/ratbagd-profile.c
- ratbagd/ratbagd-resolution.c
- src/driver-hidpp20.c
- src/driver-sinowealth.c
- src/driver-test.c
- src/libratbag-enums.h
- src/libratbag-private.h
- src/libratbag-test.h
- src/libratbag.c
- src/libratbag.h
- tools/ratbagc.py.in
- tools/ratbagctl.in.in
- tools/ratbagctl.test.in
- tools/ratbagd.py
Adds functionality to disable resolutions from a static resolution list.
Adds hidpp20 driver implementation for this functionality.
Some other minor changes, see commits.
Closes #869.
> Add functionality to disable resolutions

- doc/dbus.rst
- ratbagd/ratbagd-resolution.c
- tools/ratbagctl.in.in
Again, my oversights.
Should've been in #870.
> Some disableable resolutions fixes

- doc/dbus.rst
- ratbagd/ratbagd-device.c
- src/driver-sinowealth.c
- src/driver-steelseries.c
- src/libratbag-private.h
- src/libratbag-util.h
- src/libratbag.c
- src/libratbag.h
- tools/ratbagc.py.in
- tools/ratbagctl.in.in
- tools/ratbagd.py
Supersedes and closes #1068.
Following whot/ratbag-python#27.
> Device firmware version

- src/libratbag-util.h
- test/data-parse-test.py
- tools/merge_ratbagd.py
- tools/ratbagc.py.in
- tools/ratbagctl.in.in
- tools/shared.c
Should fix some high severity warnings.
> More refactoring to fix some CodeQL warnings

- src/driver-sinowealth.c
Some small fixes along the way.
> sinowealth: fix active profile reading on probe, and prepare for debounce time API adding

- tools/ratbagc.py.in
- tools/ratbagctl.in.in
- tools/ratbagd.py
This fixes cryptic libratbag crashes seen in #992.
> Fix ratbagctl crash if there is no active profile or no active resolution

- doc/dbus.rst
- ratbagd/ratbagd-profile.c
- src/asus.c
- src/driver-asus.c
- src/driver-sinowealth.c
- src/libratbag-private.h
- src/libratbag.c
- src/libratbag.h
- src/libratbag.i
- tools/ratbagc.py.in
- tools/ratbagctl.body.py.in
- tools/ratbagd.py
Adds API for https://github.com/libratbag/libratbag/issues/1168 and implementation for ASUS mice.
I also made UI with new options for Piper.
> add angle snapping and debounce time

- doc/meson.build
- meson.build
- pyproject.toml
- test/data-parse-test.py
- test/python-black-check.sh
- test/python-ruff-check.sh
- tools/python-black.sh
- tools/python-ruff.sh
- tools/ratbagc.py.in
- tools/ratbagctl.body.py.in
- tools/ratbagctl.devel.py.in
- tools/ratbagctl.test.py.in
- tools/ratbagd.py
- tools/toolbox.py
> Modernize Python (code review fixes)

- tools/ratbagd.py
https://github.com/libratbag/piper/pull/844
> ratbagd.py: don't mark a profile as dirty on active profile switch

- pyproject.toml
- tools/ratbagd.py
This causes crashes on Piper side.
> ratbagd.py: add back .keys() calls on all GLib.Variant

- src/libratbag-private.h
- src/libratbag.c
- src/libratbag.h
- tools/ratbagd.py
Will properly fix https://github.com/libratbag/piper/issues/470 once ratbagd.py gets updated on Piper side
> libratbag: don't apply active profile change until committing

- data/devices/sinowealth-0029.device
- data/devices/sinowealth-0051.device
- data/devices/sinowealth-1007.device
- src/driver-sinowealth.c
> sinowealth: add PMW3212 and T-Dagger Imperial T-TGM310 support

- tools/ratbagctl.body.py.in
- tools/ratbagd.py
I've actually though of adding such indicator to every property, but we only have API for the profile. I wonder if such API makes sense for every property? :thinking: I'll think about it before making a new release.
> ratbagctl: show if a profile is dirty

- src/driver-logitech-g300.c
> G300: Fix DPI Steps

- data/devices/device.example
- data/devices/glorious-model-d.device
- data/devices/glorious-model-o.device
- data/devices/sinowealth-0027.device
- data/devices/sinowealth-0029.device
- data/devices/sinowealth-0051.device
- data/devices/sinowealth-1007.device
- src/driver-sinowealth.c
- src/driver-sinowealth.h
- src/libratbag-data.c
- src/shared-macro.h
- test/data-parse-test.py
This should make it easier for people passing-by to create devices files for the sinowealth driver.
> Improve the sinowealth driver section in device files 

- src/driver-steelseries.c
More logging for errors and some clang-tidy fixes.
> Refactor steelseries

- src/driver-steelseries.c
A spectacular oversight from #1481. I have to remind myself to double check everything...
> steelseries: add missing newlines to logging

- src/driver-hidpp20.c
- src/driver-openinput.c
Few more easy clang-analyze warning fixes.
> Refactor clang analyze

- src/driver-steelseries.c
Reverts #1211, fixes #1438 and opens #888 again.
> Fix steelseries not recongnized

- data/devices/asus-rog-strix-impact.device
- src/driver-asus.c
> asus: fix single profile devices

- test/duplicate-check.py
- tools/ratbagctl.body.py.in
Fixes Ruff warnings. Ruff didn't detect these before. Should we pin Ruff version? :thinking:
> Use f-strings for formatting

- tools/ratbagd.py
- Convert strings to f-strings
- Listen and notify about RatabgdProfile.Disabled changes
> ratbagd.py: sync with Piper

- src/asus.c
- src/asus.h
- src/driver-asus.c
- tools/ratbagctl.body.py.in
Fixes https://github.com/libratbag/libratbag/issues/1509
> asus: warn on unknown key codes

- ratbagd/ratbagd.c
> ratbagd: show version when starting

- meson.build
- meson_options.txt
- ratbagd/ratbagd-device.c
- ratbagd/ratbagd.h
- rbtree/meson.build
- rbtree/src/rbtree/shared-rbtree.c
- rbtree/src/rbtree/shared-rbtree.h
I initially wanted to separate build libratbag into subfolders, but it turned out to be way too intertwined. I remember splitting it apart further, but for some reason the branch only had the rbtree moved.
> A few minor building refactorings

- data/devices/asus-rog-chakram-core.device
fixes https://github.com/libratbag/libratbag/issues/1551
> asus: add rog chakram core

- ratbagd/ratbagd-profile.c
- src/driver-hidpp20.c
- src/driver-sinowealth.c
- tools/ratbagd.py
Well, 'ratbagd-profile: cap minimum report rate to 125' could deserve a separate one. Anyway.
> Small changes not worth individual PRs

- pyproject.toml
- tools/ratbagc.py.in
> Fix new Ruff lints

- data/devices/sinowealth-0029.device
https://maddog.pl/produkty/myszki/57,mad-dog-gm905
> Add support for Mad Dog gm905
