libratbag/libratbag

- src/driver-hidpp10.c
This fixes a problem with the logitech G5
> hidpp10: make the fallback profile active and default

- src/hidpp10.c
This caused a problem since the hidpp10_device would keep a ref to
the ratbag_device - and the hidpp10_device would only get destroyed
when the ratbag_device got a ref count 0.
> hidpp10: drop internal ref counts

- src/driver-hidpp10.c
- src/hidpp10.c
- src/hidpp20.c
I hit a buffer overflow when using my M705 and using --verbose=raw. I protected against that and also dealt with a timeout issue I saw with that mouse. I did a similar but untested fix for hidpp20 - I don't have any mice with that protocol.
Also added the logitech G9 for hidpp10.
> Fixes timeout problems with M705 and adds G9

- src/hidpp10.c
- src/hidpp10.h
For supported devices this can get and set the led colors in RGB.
This patch just adds the support in the lib. Later patches will
add it to the driver and expose it in libratbag.
> hidpp10: Add support for get/set of led color

- src/driver-hidpp10.c
- src/hidpp10.c
- src/hidpp10.h
hidpp_request_command always sent short report. I added variable and switch case to use the correct size. I also changed the size for the displayed expected header, mybe there should be a define for that.
I wrote the set current resolution to test it but stopped there as I did not know to use the write_resolution_dpi op. So it is not actually tested.
I think the two other commits are trivial enough.
> Small fixes

- src/driver-hidpp10.c
This will add two G9x devices, the original and the 'Call of Duty MW3 Edition'.
> hidpp10: add G9x

- src/hidpp10.c
- src/hidpp10.h
Fixes for the 0x00 and 0x01 requests. Doesn't add anything new, it just moves from register-specific #defines to a single enum each with all the values. Nicer for a potential caller.
> hidpp10 individual features/enable hid++ reporting cleanup

- .gitignore
- src/Makefile.am
- src/driver-hidpp10.c
- src/hidpp-generic.c
- src/hidpp-generic.h
- src/hidpp10.c
- src/hidpp10.h
- src/libratbag-util.h
- tools/Makefile.am
- tools/hidpp10-dump-page.c
This branch disentangles libratbag from the hidpp10 code so we can use hidpp10 functions on their own. Useful for a bunch of debugging tools or, long-term, for providing things like pairing/unpairing tools, etc.
> hidpp10 as separate library

- src/hidpp10.c
- src/hidpp10.h
- tools/hidpp10-dump-page.c
Update the hidpp10_read_memory API to take a single byte offset.
Also increase the size of each page dump to the full 512 size.
This PR is a continuation of PR #41
> Fix dumping memory pages

- tools/ratbag-command.c
When initializing N profiles they are indexed 0 to N-1. However,
when setting the active profile to X the validation of X is a
check for X > N. Notice that N is invalid as the maximum index
is N-1.
Change the validation check of the new active profile to X >= N.
Signed-off-by: Palle Ravn <ravnzon@gmail.com>
> Correct index check in ratbag-command

- hwdb/70-libratbag-mouse.hwdb
This is untested, but should match a G5's behavior.
> Add G7 hwdb entry

- tools/Makefile.am
With -no-install present in ratbag_command_LDFLAGS, the program would
get directly copied from .libs/ratbag-command to /usr/bin, retaining
the undesired rpath tag in the ELF file.
Signed-off-by: Jan Engelhardt <jengelh@inai.de>
> build: kill -no-install for installed binaries

- TODO
- hwdb/70-libratbag-mouse.hwdb
- src/Makefile.am
- src/driver-hidpp10.c
- src/hidpp10.c
- src/hidpp10.h
- src/libratbag-private.h
- src/libratbag.c
This PR enable per device specific dpi mapping.
I was able to test only the parsing of the udev properties, but not the actual use of the table (lack of compatible hidpp10 device currently).
Please test and report your thoughts.
> hidpp10 udev resolutions

- src/driver-etekcity.c
- src/driver-hidpp10.c
- src/driver-hidpp20.c
- src/driver-roccat.c
- src/driver-test.c
- src/libratbag-private.h
- src/libratbag-test.h
- src/libratbag.c
- test/test-device.c
This driver stub feels wrong. We can infer most of the capabilities by looking into the device. If a device has more than one profile, it is obvious is supports switchable profiles.
Plus this allows to have a common capability check between the drivers.
Submitting as a PR for comments before the merge.
> Remove has_capability driver stub

- src/driver-etekcity.c
- src/driver-hidpp10.c
- src/driver-hidpp20.c
- src/driver-test.c
- src/libratbag-private.h
- src/libratbag.c
- src/libratbag.h
- src/libratbag.sym
- test/test-device.c
- tools/ratbag-command.c
We do not have any driver using it, and we are not sure this will even
be required. Before releasing a version with this, remove it. We
can always re-add this later if the need appears.
API change, so submitting it as a PR.
> Remove the default profile capability

- src/driver-hidpp10.c
There are 10 buttons defined in the profile but only 9 physical
buttons. LGS also only allows to configure 9 of them. Button 5
is the "dead" button in the list.
> hidpp10: Add button mappings for G9

- src/libratbag.c
- src/libratbag.h
Designates a device that can be queried for the current configuration. Some
devices lack this ability so we rely on the caller to upload a known
configuration to the device before we can really proceed.
Set by default, devices without that capability should be the exception, not
the norm.
This patch just adds the capability, actual handling for this needs to be
added when we add the first device without this capability.
> Add a QUERY_CONFIGURATION capability

- src/driver-hidpp20.c
- tools/hidpp20-dump-page.c
The G602 fails at retrieving feature 0x2201. This is not an issue as the info will be in the profile itself (hopefully).
Also fixes an embarrassing segfault with hidpp20-dump-page when called against a non hid++ 2.0 device.
> G602 fixes

- src/hidpp-generic.h
- src/hidpp10.c
Was off by one, the message content only includes one byte of extra information
before the serial number. And add a BE 32-bit helper while we're at it.
> hidpp10: fix fetching of serial number

- hwdb/70-libratbag-mouse.hwdb
- src/hidpp20.c
Added the product ID for the new G502 (with rgb LEDs) in hwdb. I hope I guessed correctly the version from the already present G502 product ID.
The profile format seems to be the one already supported. I will test that more later.
While reading the code I also found a incoherent comparison, I added the obvious bit shift, it looks coherent with the value in my G502's description.
> Added G502 support and small fix

- hwdb/70-libratbag-mouse.hwdb
- src/Makefile.am
- src/driver-gskill.c
- src/libratbag-private.h
- src/libratbag-util.c
- src/libratbag-util.h
- src/libratbag.c
This contains the new driver for the G.Skill MX780 mouse, and implements all of the functionality that libratbag presently supports. In addition, we add a "reset" capability to libratbag that allows one to request that the mouse reset a profile to manufacturer's default. The main reason for this functionality is because this mouse gets a little upset if it has an improperly written profile, and the windows G.Skill configuration program is actually broken enough that I wasn't able to rely on just using that for resetting profiles.
I'm going to probably start working on additional features as well such as hooking the refresh rate in libratbag up to something, liftoff value support (since it seems to be a common enough function), etc. but for now this seems pretty good :).
> Support for the G.Skill MX780

- src/driver-gskill.c
Noticed this while adding support for profile commits. This is definitely
a bug.
Signed-off-by: Lyude <thatslyude@gmail.com>
> gskill: Update checksum *after* updating profile name

- src/libratbag.c
Supersedes #107 as the commits depends on each other.
a) We currently mark the profile as dirty even if nothing changed. We should not write unnecessarily to the device. This fixes things for the resolutions at least. Buttons are still todo
b) Unset the previous default on other resolutions when setting a new.
> Misc resolution fixes

- src/libratbag.c
Without the capability RATBAG_RESOLUTION_CAP_INDIVIDUAL_REPORT_RATE we should update the report rate on all resolutions.
As far as I can see we do not have per-resolution report rate on any of the drivers. The API exposes the report rate on the resolutions though, so we need to keep on supporting that. The new code is a bit messy. Should we have a per-profile variable to use when the capability is not set? Or is it worse to have a variable on both profile and resolutions then?
> Update report rate on all resolutions if needed

- src/driver-gskill.c
- src/libratbag-private.h
- src/libratbag.c
- src/libratbag.h
- src/libratbag.sym
- tools/ratbag-command.c
This allows us to enable and disable profiles on mice which support it. As well, this includes the required modifications to support this with the G.Skill driver. This is pretty nice since we can get rid of the ugly hack of enabling all profiles that we've had to use in the driver.
> Add the ability to disable profiles

- src/hidpp10.c
In hidpp10_get_hidpp_notifications(), we want all three bytes from
parameters[], not parameters[0] twice. This matches
hidpp10_set_hidpp_notifications().
Signed-off-by: Stephen Kitt <skitt@redhat.com>
> Copy all three bytes from parameters

- hwdb/70-libratbag-mouse.hwdb
- src/Makefile.am
- src/driver-logitech-g300.c
- src/libratbag-private.h
- src/libratbag.c
Supports the common functionality exposed by libratbag:
- selecting profile 1-3 (profiles cannot be disabled)
- selecting resolution 1-4 (can also not be disabled)
- report frequency
- default resolution per profile
- button actions: mouse button numbers or key+modifier
(modifiers are just a bit field and can easly be set
in the driver, but not included as libratbag does not
support it yet)
- LEDs are not yet hooked up but are just a table of 7
different predifined colors.
- Seting active profile and resolution are both implemented
but only profile activation is in use. The resolution
activation code is commented until supported from libratbag
itself.
The G300 has an unusual way of numbering buttons:
Left:1, Right:2, Middle: 3
The purpose of report type 0xF2 is not known.
> Add driver for the Logitech G300/G300s

- tools/shared.c
This doesn't effect functionality (since assigning this action to buttons seems to do nothing on the MX Master at present), but the ratbag-command program should at least know the action's name.
> Teach ratbag-command the "ratchet mode switch" special action name

- data/logitech-g303.svg
An SVG of the Logitech G303 mouse, can also pass as the G302 as very little difference between models
> add SVG Logitech G303 data

- configure.ac
We only have two auto-detected dependencies, for documentation and tests. During the work with meson I realised this is not really a good solution. Our dependencies should be well-defined for what is considered 'normal' and explicitly defined for any deviation from that normal build.
The normal build *includes* docs and tests, because we expect developers to find errors in either. A distribution build may exclude either or both, but it should be explicitly specified by the distribution rather than having our build system guess what's not needed.
So this PR removes the auto-detection for doc/test builds and replaces them with a default enabled.
> Remove auto-detection of features from configure.ac

- src/libratbag-hidraw.c
- tools/hidpp10-dump-page.c
- tools/hidpp20-dump-page.c
- tools/ratbag-command.c
Few defects detected by compiling the rpms
> Fix warning: ‘x’ may be used uninitialized in this function

- README.md
- doc/libratbag.doxygen.in
- meson.build
Fixes source detection for documentation rebuilds, drops the doxygen tags from the readme and breaks up two long messages
> documentation cleanups

- src/hidpp-generic.h
- src/hidpp10.h
- src/hidpp20.h
- src/liblur.h
- src/libratbag-hidraw.h
- src/libratbag-private.h
- src/libratbag-test.h
- src/libratbag-util.h
- src/libratbag.h
- src/usb-ids.h
- tools/shared.h
Now that we use meson exclusively and meson uses this for its config.h, you
wouldn't get around it anyway. Besides, the main compilers support it and
libratbag is too niche to worry about others.
> Replace ifndef include guards with pragma once

- tools/ratbag-command.c
- tools/shared.c
The help calls the mode "breath" and the mode will also be reported
as such (via led_mode_to_str).
If you prefer it the other way around (rename other locations to "breathing"), let me know.
> tools: rename led mode from breathing to breath

- src/driver-hidpp20.c
When using the G502 without RGB LEDs, the feature 8070 is not here.
And this segfaults :)
Signed-off-by: Benjamin Tissoires <benjamin.tissoires@gmail.com>
> hidpp20drv: fix segfault with G502

- src/hidpp20.c
- src/hidpp20.h
First part of fixing #122.
Still missing the dynamically allocation of the sector size, but at least now the hidpp low level calls are correct.
Currently the G402 will not work with libratbag if the sector size is different because we reject any device that has a sector size different than 256.
> hidpp20: take into account sectors on 16bits

- release.sh
Cleanup of release.sh, and I must say, why would you not run this script in the current
directory.
> release.sh: remove unreachable test now that we switched to meson

- src/libratbag.h
This makes code that just checks for general abilities easier to write, the
specific thing we can do (e.g. switch profiles) is expressed as separate bit.
This is an ABI break
Related to #172
> Group the the capabilities and provide some more generic topic-like caps

- README.md
- circle.yml
Semaphore CI is still using Ubuntu 14.04, and the shipped systemd version is just too old.
OTOH, Circle CI 2.0 (still beta as of today) allows to use any docker image as a base for running the tests. Meaning that we can have a fedora rawhide image as a base and we do not have to handle the update of systemd meson and others.
Ship a basic circle.yml for Circle CI to run our tests and add the badge in the README.
In the future, this could also allow us to add other distribution as base, so we could run and fix the tests on those other distributions.
> Add circle.yml

- circle.yml
Circle CI uses docker, so nothing prevents us from running several tests in parallel for different distributions. Ideally, we should also be able to test the install and be sure we can talk to ratbagd with the dbus activation on those various distributions.
This version runs both Fedora rawhide and Ubuntu 17.04 at the same time.
> enhance circle.yml with workflows and parallel tests

- meson.build
Fedora uses /usr/lib64 as libdir but systemd uses /usr/lib for its files. We
used libdir to install the unit files, which then end up in
/usr/lib64/systemd/systemd where it will be ignored. There's no good way to
avoid this beyond detecting lib64 for this use-case and hacking around it.
https://github.com/libratbag/libratbag/issues/188
> meson: hack around Fedora's systemd libdir confusion

- meson.build
> meson: fix svg data dir

- circle.yml
It doesn't cost much to actually install the files, so we can check where they are installed.
Also add mesonconf before building so we can see in the logs the various configure environment.
> circle.yml: add install step

- circle.yml
Try to uninstall and see if there are leftovers.
Currently the tests fail as `/usr/share/ratbagd` is not uninstalled.
I couldn't find out what magic is required for it to be removed by meson, so submitting the PR in the hope someone tells me what to fix in `meson.build`.
> circle.yml: uninstall and checks if there are any leftovers

- ratbagd/ratbagd-resolution.c
ratbagd unconditionally called set_resolution_xy while libratbag expects the caller to check on the  apabilities. Instead of letting this burden to the dbus user, have rabtagd handle this for us.
> ratbagd: call the correct set_resolution based on the capabilities

- ratbagd/ratbagd-profile.c
- ratbagd/ratbagd-resolution.c
Leave the signal in the DBus API for now so we can hook it up later, but
stop the signal being generated. Changing the dpi does not change the active
resolution.
https://github.com/libratbag/libratbag/issues/205
> ratbagd: drop the ActiveResolutionChanged signal generation

- tools/ratbagctl.in
File "./build/ratbagctl", line 713, in main
cmd.func(r, cmd)
UnboundLocalError: local variable 'r' referenced before assignment
> tools: fix ratbagctl error when dbus isn't available

- DBusInterface.md
- ratbagd/ratbagd-device.c
- ratbagd/ratbagd.c
- ratbagd/ratbagd.h
Two new DBus interfaces:
org.freedesktop.ratbagd1.Manager.Themes -> string array
org.freedesktop.ratbagd1.Device.GetSvg('theme') -> string
The Themes property is a static list of available themes. These are currently
hardcoded in ratbagd, but the theme 'default' is guaranteed to exist.
The GetSvg() method takes a theme name and returns the full file path to the
themed SVG.
Longer-term this will deprecate the Svg and SvgPath properties in the Device
but for now we leave them there.
https://github.com/libratbag/libratbag/issues/204
> Add theming support to ratbagd

- hwdb/70-libratbag-mouse.hwdb
The G403 comes in a (optional) wireless version too; the dongle
that come with it has the product id c539, which is already
handled and also works (by the G900) entry.
Signed-off-by: Christian Kellner <christian@kellner.me>
> hwdb: add G403 entry

- data/gnome/README.md
- data/gnome/logitech-g403.svg
- data/gnome/logitech-g502.svg
- data/gnome/logitech-g700.svg
- meson.build
During a discussion I had with [Jakub Steiner](http://jimmac.musichall.cz/) he suggested we use toned-down device SVGs instead. Both @whot and I like this approach, so let's discuss this with the rest! This is a first device he did for us, which is the G403 that I own so I can use it while working on Piper.
The mockups aren't entirely up-to-date (will fix that tonight or tomorrow, most likely) but [this](https://hjdskes.github.io/img/blog/gsoc-part-4/mousemap_toned_down.png) is where we're going (that's still proof of concept code that I'll extend in the next few days). As you can see, we will need to retrieve some coordinates from the SVG to place the labels. This is why I also updated the guidelines. I also made the canvas size smaller (simply took what Jakub gave me, it looks good) …
> Use toned-down device SVGs

- data/gnome/logitech-g500.svg
- data/gnome/logitech-g500s.svg
- data/gnome/logitech-g700.svg
- hwdb/70-libratbag-mouse.hwdb
- meson.build
Still WIP, do not merge yet. But I open the pull request for discussion.
The `text-align` properties are not set on the leaders. I did not find how to add that on rectangles in Inkscape.
I named the layers but that set the `inkscape:label` attribute not the `id` one. I guess the `id` is needed although the readme is not clear about that.
For the main buttons, I added open paths (copied from the light gray area) so there is no border on the bottom. The buttons should be there although not visible.
Since the G500 and the G500s are exactly the same when removing details. They should use the same file. Because of the themes I cannot set the same svg file from the hwdb, so I added a symlink. What is the preferred way to achieve that? meson installs a copy of the file instead of the symlink. …
> data: add toned-down SVG for Logitech G500/G500s

- .flake8
- meson.build
- ratbagd/ratbagd.c
- ratbagd/ratbagd.h
- src/driver-hidpp20.c
- src/driver-test.c
- src/libratbag-private.h
- src/libratbag-test.c
- src/libratbag-test.h
- src/libratbag.c
- tools/ratbagctl.devel.in
- tools/ratbagctl.in
- tools/ratbagctl.test.in
Well, there are still a few FIXMEs here and there, but better sending this one out before it gets too much of a beast.
The idea is to instantiate a driver-test libratbag element, and playing with unit tests to see if we messed up the parsing of rabtagctl.
This gives a good idea if ratbagctl/ratbagd works as expected.
The current test run takes roughly 21 seconds on my machine, most of the time is spent by forking, initializing the bus, and settings the devices, etc...
I have a local version that creates only one dbus connection and directly calls the parsing/function from ratbagctl. This version runs in less than a second but fails because ratbagctl python binding doesn't listen for signals and can't update its internal state. I tried playing with the GLib.MainLoop, without success.
> ratbagctl rewrite and test suite

- src/driver-hidpp20.c
- src/hidpp20.c
Partially fixes issue #124.
Remapped buttons were diverted at the same time, resulting in a disabled button (diverted buttons don't send their remapped event).
This fixes both remapping the button and changing the divert state correctly.
> Fix HID++2.0/1b04 divert and remapping

- src/driver-etekcity.c
- src/driver-gskill.c
- src/driver-hidpp10.c
- src/driver-hidpp20.c
- src/driver-logitech-g300.c
- src/driver-roccat.c
- src/libratbag.c
Any specific capability like 'switchable resolution' requires the basic
'resolution' capabilty to be set.
Related to https://github.com/libratbag/piper/pull/35
> Set the parent capabilities before setting any child ones

- ratbagd/ratbagd-resolution.c
See https://github.com/libratbag/piper/pull/36#issuecomment-315065722
The only issue now is that the signal is only emitted on the resolution that has just been set the default. At the very least it should also be emitted on the resolution that *was* the default, but I don't think this is currently possible so we'll have to go with emitting it on all resolutions. What's the best way to go about this?
(We should probably do this for other signals too.)
> RatbagdLed: emit DefaultResolutionChanged on the resolution's object path

- circle.yml
Otherwise we get build errors when rawhide is broken, like today. Not worth
chasing that moving target.
> circleci: use fedora-latest, not rawhide

- data/gnome/logitech-g502.svg
Noticed this while checking for similar issues as the one described in https://github.com/libratbag/piper/issues/48.
> data/gnome/logitech-502.svg: fix text alignment of button5-leader

- ratbagd/ratbagd-led.c
- ratbagd/ratbagd-profile.c
Was using 'b0' as enumerator, copy-paste error from the button code. Switch to
'l0' to make it easier to differentiate in d-feet or other dbus viewers.
> ratbagd: change the led path to .../event4/p0/l0

- DBusInterface.md
- ratbagd/ratbagd-device.c
- ratbagd/ratbagd-led.c
- ratbagd/ratbagd-profile.c
- ratbagd/ratbagd-resolution.c
- ratbagd/ratbagd.c
- ratbagd/ratbagd.h
- tools/ratbagctl.in
- tools/ratbagd.py
This is on top of #241 and should only be merged when that one is merged.
When I started tidying up the DBusInterface.md document I noticed a fair few inconsistencies with the API. A few basically superfluous calls and some imbalanced property handling (having a 'foo' readonly property but a SetFoo() method - instead we can just make the property read-write).
Note that his is not complete but I'm about to head out for GUADEC, so better to get this in now. The bits missing are changing the Button interface from using strings to using the libratbag enums and the LED type string to an enum too.
ratbagd.py will need to be synced to piper after merging this but no client changes are needed, this is all handled within the bindings.
> DBus interface revamp

- tools/ratbagctl.in
No need to have two copies here, simply have the dict and then flip it so it
works with the strings as keys too.
The slightly odd list comprehension is because we can't add to a dictionary
while iterating through it, so we need to get everything out first.
> Reduce to one special->special string mapping dictionary

- meson.build
Configuring with 'meson builddir' would fail with:
Program build/ratbagctl.test found: NO
Meson encountered an error in file meson.build, line 512, column 0:
Program "build/ratbagctl.test" not found or not executable
> meson: allow builddir other than 'build'

- tools/ratbagctl.test.in
On CircleCI, the builds fail one over four times because we are launching
the testsuite while ratbagd.devel is still not ready.
Do a basic polling after we launch the daemon so that we are aware when
the ratbagd daemon is ready.
> make sure the dbus daemon is available before starting the test suite

- DBusInterface.md
- ratbagd/ratbagd-button.c
Internally, setting mappings changes the action type but this isn't reflected on DBus because ratbagd doesn't emit the PropertyChanged signal for them.
> Emit PropertyChanged signals for AcitonType when setting button mappings

- meson.build
- tools/ratbagctl.devel.in
- tools/ratbagctl.in
- tools/ratbagctl.test.in
- tools/toolbox.py
Few things I have been working on today:
- have a more common way of launching ratbagd from `ratbagctl.{devel|test}`
- do not spawn a subprocess to run a python script
The name `toolbox.py` is terrible but I couldn't find a better one.
> ratbagctl tools fixes

- ratbagd/ratbagd.c
If we emit the changes before unlinking the device, the list of devices hasn't actually changed yet and Piper cannot figure out which devices have been removed. Hence, we simply unlink the device before emitting the signal and all is good again.
> ratbagd.c: unlink before emitting property changed

- ratbagd/ratbagd-resolution.c
This allows clients to respond to changes in the active resolution. It's not the cleanest approach, but it works. To clean it up, we could cache the changed resolutions and make sure to only emit the signal on those, just as the FIXME already notes.
References https://github.com/libratbag/piper/pull/132.
> RatbagdResolution: emit properties changed from signal callbacks

- src/driver-hidpp20.c
- src/hidpp-generic.c
- src/hidpp-generic.h
- src/hidpp10.c
- src/hidpp20.c
libratbag was printing ERR_INVALID_ADDRESS when it should have been ERR_INVALID_ARGUMENT (a detail from issue #280). This should fix some misleading error messages.
I have left the HID++1.0 error codes in hidpp-generic since they are used in hidpp20.c (for checking the protocol version), but the HID++2.0 error codes could be moved in hidpp20.h if you prefer.
I also extended the string arrays because the value 0xFF was previously excluded but not checked before accessing the array.
> Add HID++2.0 error codes

- tools/ratbagctl.in
Don't automatically handle the help output - call print_help() on the parser
manually.
It's unclear why this doesn't just get called correctly, but at least this
fixes the immediate issue. The subcommand help is still pretty terrible
though.
https://github.com/libratbag/libratbag/issues/288
> ratbagctl: improve the top-level --help output

- DBusInterface.md
- ratbagd/ratbagd-button.c
- tools/ratbagd.py
This brings RatbagdButton in line with the other Ratbagd* objects, and
more importantly solves https://github.com/libratbag/piper/issues/140.
> RatbagdButton: make mapping properties writable

- tools/ratbagctl.devel.in
- tools/ratbagctl.in
keeps the ratbagd.devel instance alive so we can run easily piper against the test devices.
best use is something like `./build/ratbagctl.devel --keepalive list` and then connect piper.
> add --keepalive to let piper use ratbagd.devel

- tools/ratbagctl.devel.in
- tools/ratbagctl.in
I originally intended to have a dynamic use of argparse to generate the commands, but it turned out to be a nightmare.
Just go down the tree of arguments and format the help properly, and have the same crazy output than the one in ratbag-command.
Fixes #288
> fix help behavior

- tools/ratbagctl.devel.in
- tools/toolbox.py
If we couldn't find the name on the bus or the ratbagd process already
terminated, return None and fail.
> tools: don't return a ratbagd_process if things failed

- src/libratbag-data.c
If the error variable is not reset then we may end up freeing it
again in the next block. This can cause problems later for glib.
Fixes #311
> reset GError before reuse

- src/libratbag-data.c
Before 340e5b7d86fc9cc04dc563dc755d1efffe9a97c5 I got:
ratbag error: libratbag bug: Logitech G9 Laser Mouse: no profile set as active profile
No supported devices found
After 340e5b7d86fc9cc04dc563dc755d1efffe9a97c5 I get:
ratbag error: Unable to locate device files: No such file or directory
ratbag error: Unable to locate device files: No such file or directory
ratbag error: Unable to locate device files: No such file or directory
No supported devices found
With this PR we give a hint to the user about where libratbag is looking for the files.
> improve error for missing device files

- ratbagd/ratbagd-profile.c
- ratbagd/ratbagd.c
- src/driver-test.c
- src/libratbag-private.h
- src/libratbag-test.h
- src/libratbag-util.h
- src/libratbag.c
- src/libratbag.h
- src/libratbag.sym
- tools/ratbagctl.in
- tools/ratbagctl.test.in
- tools/ratbagd.py
- tools/toolbox.py
Finally, profiles can exist and have a name.
Currently no driver implements the feature because -ETIME.
fixes #266
> profiles name support

- data/gnome/fallback.svg
- meson.build
- ratbagd/ratbagd-device.c
- ratbagd/ratbagd.c
This SVG is generic enough to cover 7-button mice with up to 3 LEDs that are
supported but don't have an SVG. The SVG style is intentionally NOT a generic
mouse to make it obvious that something isn't right here. If we use a generic
mouse, people may not put the effort into a proper SVG style because the
generic mouse is good enough.
The fallback is currently only used for test devices
> data: add a fallback.svg file

- ratbagd/ratbagd-profile.c
- ratbagd/ratbagd-resolution.c
We sent a useless signal, but didn't update the actual properties.
> Fix sync of ratbagd profile IsActive properties

- meson.build
Since we no longer install ratbag-command itself, there isn't much
point installing its manpage.
Signed-off-by: Stephen Kitt <steve@sk2.org>
> Don't install ratbag-command manpage

- src/driver-logitech-g300.c
The profile ID's used are:
profile 0: 0x80
profile 1: 0x90
profile 2: 0xA0
These were miscalculated as 0x80, 0x81, and 0x82.
> G300: fix profile switching

- tools/merge_ratbagd.py
- tools/ratbagctl.devel.in
Initially I thought both ratbagctl and .devel where affected, but it turns out we are just trying to kill ratbagd too soon in ratbagctl.devel. This appeared when we switched to async commits in ratbagd.py.
Adding also a commit that fixes permissions for rabtagctl on my setup (Fedora 26).
> fix commit() when using ratbagctl.devel

- DBusInterface.md
- ratbagd/ratbagd-button.c
- tools/ratbagctl.in
- tools/ratbagctl.test.in
- tools/ratbagd.py
Plan is to remove the key mapping altogether and make it transparent from the
Macro mappings (in libratbag/the drivers). Meanwhile, remove the DBus API so
nothing can actually start using it.
This replaces #322
> ratbagd: Drop KeyMapping from the DBus interface

- tools/ratbagd.py
Cleanup after afaf3fa83ddeeffce6a911225f7170afeba71be5, I missed this in my review.
> tools/ratbagd: remove KeyMapping methods

- src/hidpp20.c
The feature discovery code is bugged for HID++2.0. The feature set count does not include the root feature. 
This would result in the last feature not being correctly discovered by libratbag.
> hidpp20: fix last feature discovery

- meson.build
- src/driver-hidpp20.c
- src/hidpp20.c
- src/hidpp20.h
- src/libratbag-private.h
- tools/hidpp20-dump-page.c
- tools/hidpp20-reset.c
- tools/ratbag-command.c
Fixes both #280 and #122 (hopefully).
This is the first step required before we are finally able to write macros on the device.
The "new" memory API only allows full sectors to be read/written. This ensures we always write the crc and check for it.
Also, now we better detect if the device is using factory profiles or not (see #280).
I still haven't yet implemented caching for the memory. This will be required for macros and to speed up a little bit the parsing of the device.
Please test!
Note: I also quickly wrote a tool to reset the memory to 0x00. This is hopefully the factory default (can't remember if this is true or not).
> hidpp20 memory rework

- src/hidpp20.c
The feature discovery was corrected in a previous commit. 
However the code still stores the wrong size.
> hidpp20: store correct size for feature list

- data/gnome/logitech-g300.svg
- meson.build
A SVG for the G300 for GNOME theme. It works fine in the buttons view but only one of the leaders is shown on the resolutions view. Not sure why. check-svg.py does not complain.
I did not include the LED yet as I have not yet added it in the driver.
> SVG for G300 in GNOME theme

- src/driver-hidpp20.c
This should fix #343 without impacting the mice without onboard profiles.
> hidpp20: fix resolution count detection

- tools/ratbagd.py
So we at least don't crash, see #383. Alternatively, we could catch `ACTION_SPECIAL_INVALID` before doing the lookup if you don't want this internal error showing up to the outside world.
I'll sync this to Piper when it gets merged.
> ratbagd: add ACTION_SPECIAL_INVALID to the table

- ratbagd/ratbagd-button.c
I missed this one in #336, see https://github.com/libratbag/piper/issues/176.
> RatbagdButton: fix missed dbus return value

- src/driver-logitech-g300.c
Writing multiple changed profiles was broken as we would exit the
loop after the first profile write. We were returning the number
of bytes written and this was interpreted as an error.
Fix it my returning 0 when we have written the correct number of
bytes to the mouse.
> G300: fix writing multiple profiles

- src/driver-logitech-g300.c
It was implemented but never used before. Use it when writing the
active profile.
> G300: set the active resolution

- src/driver-logitech-g300.c
Needed for piper to show the DPI slider for the resolutions.
> G300: set min/max DPI

- src/libratbag-private.h
Add a comment that drivers are expected to initialize and
read all profiles in the probe callback.
Fixes #333
> expand documentation of probe call

- src/libratbag.c
Even if there is only 1 LED we should set the cap to let Piper change it in the GUI
> set CAP_LED for mice with only 1 LED

- meson.build
- ratbagd/ratbagd.c
- tools/ratbagctl.devel.in
- tools/toolbox.py
Fixes the exception when ratbagd.devel doesn't start up properly. And avoids the journal being filled up with backtraces
> ratbagd.devel tidyup

- data/devices/logitech-g9.device
- data/gnome/logitech-g9.svg
- meson.build
Add a SVG for the logitech G9 for the gnome theme. It passes the check script and works in piper.
> G9: add .svg for GNOME

- src/driver-hidpp20.c
- src/driver-logitech-g300.c
- src/libratbag.c
- src/libratbag.h
- tools/ratbagctl.in
- tools/ratbagd.py
1-bit RGB is needed for the Logitech G300, let's rename the main RGB to
indicate how many bits we actually have.
See #335
> led: change RGB to RGB888 and add 1-bit RGB

- meson.build
- test/test-context.c
- test/test-device.c
- test/test-iconv-helper.c
- test/test-util.c
- tools/ratbagctl.test.in
It's a fixed value so it's much easier to set this in the test binaries rather
than requiring the user to set this in the env before running a test manually.
> test: set RATBAG_TEST in code, not in meson

- src/driver-hidpp10.c
- src/hidpp10.c
This fixes writing profiles on the G9. The problem was when setting the current resolution, which is a short report on the G9 but a long on other models. While looking into it I noticed that we are getting/setting the current resolution unnecessarily many times, and that we set it before the profile write which causes the device to jump to its default resolution.
> G9 fix commit

- src/driver-hidpp10.c
write_profile is deprecated and none of the other drivers have an empty
implementation like this.
> hidpp10: remove empty callback

- data/devices/logitech-g403-wireless.device
Resolves #384. Confirmed [under Solus](https://dev.solus-project.com/R3780:07a0590216760778cfd272f40fc79d17f7325ac9) while packaging.
> Correct G403 ID. Added Wireless-specific G403 device file.

- data/devices/logitech-g9.device
- src/driver-hidpp10.c
- src/hidpp10.c
With this the LEDs can be read and written on the G9.
The G9 is as far as I know the only hid++1.0 mouse with RGB LED. The
other mice are monochrome.
> hidpp10: Fix LED read/write

- doc/dbus.rst
- ratbagd/ratbagd-resolution.c
- ratbagd/ratbagd-test.c
- src/driver-hidpp10.c
- src/driver-hidpp20.c
- src/driver-logitech-g300.c
- src/driver-test.c
- src/hidpp10.c
- src/hidpp10.h
- src/libratbag-private.h
- src/libratbag-test.h
- src/libratbag.c
- src/libratbag.h
- test/test-device.c
- tools/ratbag-command.c
- tools/ratbagctl.in
- tools/ratbagctl.test.in
- tools/ratbagd.py
This builds on top of #392 
Changes from a dpi min/max to a discrete list of "here are the resolutions we support". This makes it easier for clients to do the right thing.
> DBus API change to switch to discrete resolution lists

- circle.yml
Note that the push requires a specific private key in the libratbag circle CI organization, meaning that only the master branch of libratbag will be allowed to push to the doc repo.
Note also that only the master branch will trigger the request:
- any PR will not trigger the request
- any push on the master branch of a personal repo will fail while attempting to write the docs, if the repo is setup to use circleCI too.
> circle.yml: deploy docs when the master branch is updated

- circle.yml
We don't really need to redownload everything for all the various fedora jobs.
Launch an extra Fedora job that retrieves and store the DNF cache, and then make use of it in the rest of the workflow.
We do not gain much right now in term of time spent. We should get a rough 1 min when deploying the docs though on the master branch.
This goes on top of PR #394.
> circleCI: cache DNF data accross jobs

- src/libratbag-enums.h
Replacing the doctext where they should be in enum ratbag_led_mode.
> enums.h: few doc fixups

- doc/dbus.rst
- ratbagd/ratbagd-led.c
- src/driver-hidpp20.c
- src/driver-test.c
- src/libratbag-private.h
- src/libratbag.c
- src/libratbag.h
- tools/ratbagctl.in
- tools/ratbagctl.test.in
- tools/ratbagd.py
To be able to query which modes are available.
Exposed via ratbagctl as
./build/ratbagctl.devel led 0 capabilities event4
> Add ratbagd_led_has_mode() and the required dbus additions

- doc/dbus.rst
- ratbagd/ratbagd-resolution.c
- ratbagd/ratbagd-test.c
- src/driver-etekcity.c
- src/driver-gskill.c
- src/driver-hidpp10.c
- src/driver-hidpp20.c
- src/driver-logitech-g300.c
- src/driver-roccat.c
- src/driver-test.c
- src/hidpp20.c
- src/hidpp20.h
- src/libratbag-private.h
- src/libratbag-test.h
- src/libratbag.c
- src/libratbag.h
- src/libratbag.i
- test/test-device.c
- tools/ratbagc.py
- tools/ratbagctl.1
- tools/ratbagctl.in
- tools/ratbagctl.test.in
- tools/ratbagd.py
Basically the same approach as for the dpi list we already have. Some of the rates are hardcoded, but we can fill those in later.
And a bunch of cleanup patches.
> Add a list of supported report rates to the resolution

- data/devices/logitech-g403-wireless.device
- data/devices/logitech-g403.device
This is in response to a comment on PR #385 suggesting that G403 device files be merged and just use multiple IDs on DeviceMatch.
Confirmed to work, built against git and checked with my G403 `usb:046d:c083`
> Merge Logitech G403 devices files.

- doc/meson.build
Some vendors (*such as Solus*) ship python3 sphinx binaries without a `-`, so let's check for both.
> docs: Ensure we also check for python3 sphinx build exec suffixed without a hyphen

- data/gnome/logitech-g300.svg
The leader for the LED was on the buttons layer. It does not seem to make any difference in Piper but let's be correct anyway
> G300: move LED leader to LEDs layer

- meson.build
No-one appears to be using these and the efforts to create SVGs
go into the GNOME ones (used by piper). Leave them in the git tree in case
someone wants to pick them up but until we have a consumer it's not worth it
installing them.
Note: this kinda bears the question now whether we should even bother claiming to have a 'default' theme...
> Don't install the default theme svgs

- tools/valgrind-ratbag-command.supp
Fixes #405
Now the valgrind output is clean. Let's hope this will not hide some memleak :/
> Valgrind: shut up some non relevant memory leaks

- meson.build
- ratbagd/ratbagd-device.c
- src/libratbag-data.c
When using ratbagctl.devel we would use the .device files
from the source dir. This patch also makes it use the .svg
files from the source dir. This makes it easier to edit the
svg and less surprising now that it follows the .devices files.
We need to treat the .device and .svg file a bit different. The
reason is that in soure the device files are in a separate dir
'data/devices' but we do not use the 'devices' dir when installed.
> use SVGs from the source dir in .devel

- tools/ratbagctl.test.in
As the comment says, this skips an unrunnable test. Useful when creating a package.
> Allow meson to skip the test that requires root if root is unavailable

- src/hidpp20.c
Since the firmware refuses to accept profile dictionnary with all profiles disabled, this enables the first profile in the dictionnary in case all profiles are disabled. This fixes #428 by fixing the case where a mouse is plugged in with all profiles disabled. 
> Force at least one profile to be enabled on Logitech mice

- ratbagd/ratbagd-profile.c
- ratbagd/ratbagd-resolution.c
This makes sure that every boolean passed to sd_* functions is 4 bytes long as required by the dbus specification
> ratbagd: ensure boolean passed to sd_* are 4 bytes wide

- dbus/org.freedesktop.ratbag1.conf.in
- meson.build
- meson_options.txt
This change makes it possible to pass '-Ddbus-group=<group>' to limit
the access to the ratbagd D-Bus service. The default remains to allow
everyone access to the service.
This allows integrators to choose more conservative security settings
e.g. only allowing users in the 'games' group to talk to the ratbagd
daemon.
> meson/dbus: support build time option to restrict D-Bus access

- src/libratbag.c
We were only resetting the dirty flag for profiles and buttons on commit.
> reset LED dirty flag on commit

- src/driver-steelseries.c
ratbag_hidraw_output_report returns 0 on success, not the number of bytes written
> steelseries: correct use of return code

- src/driver-steelseries.c
The steelseries mice have 2 resolutions. The range/interval
is different per device. We cannot query the devices, so we
have to pick some defaults. Before we took the two first in
the list to be safe. It is a pretty bad default though. Using
800 and 1600 is supported by all known devices and seem as
more reasonable defaults.
> steelseries: default resolutions to 800/1600

- src/driver-steelseries.c
The original Rival and earlier versions did not support cycle mode on the device.
> steelseries: set LED capabilities

- data/devices/steelseries-kinzu-v2.device
- data/devices/steelseries-rival-310.device
- data/devices/steelseries-rival.device
- data/devices/steelseries-sensei-310.device
- src/driver-steelseries.c
- src/libratbag-data.c
- src/libratbag-data.h
I need to store in the .device file for the steelseries mice whether they support mapping buttons to keys or not. I cannot query it and it the feature does not follow any of the other settings, like DeviceVersion.
The steelseries mice do not support storing real macros on the device itself, only key+modifiers. This can be seen as a single-step macro. Since it seems we will need a global option for macro length anyway I thought that using a macro length of 0 could be used to indicate that no keys can be set.
I have only updated the .device files for the steelseries mice in this PR.
Is it a reasonable option? And is there a better name than MacroLength?
> Add MacroLength to .device files

- src/driver-logitech-g300.c
- src/driver-steelseries.c
- src/libratbag-private.h
- src/libratbag.c
This expands the approach in #402 to also cover modifier keys, and goes for a full conversion to macros instead of converting to/from the key binding action. The drivers can use the functions to convert between a key+modifier bit field and a single key press macro.
The second patch is a conversion of the logitech-g300 driver.
> Helpers for conversion betwen macro and key+modifier binding

- src/driver-logitech-g300.c
Set the on/off LED mode caps for G300
> logitech G300: set LED mode capabilities

- dbus/org.freedesktop.ratbag1.service.in
The alias can be used only when the service is enabled
> dbus service: use the actual ratbagd service name and not the alias

- meson.build
This is needed for future versions of meson
> meson: use three single quotes for multiline strings

- ratbagd/ratbagd-resolution.c
RATBAG_RESOLUTION_CAP_SEPARATE_XY_RESOLUTION is a part of
ratbag_resolution_capability.
> ratbagd: use correct enum type

- src/hidpp10.c
value and dpi are unsigned so the delta calculations was wrong when
dpi is larger than than value. Casting to int should be fine for the
expected range of values in those variables.
> hidpp10: fix finding the closest dpi

- src/driver-steelseries.c
Adding a short sleep between calls makes the writes to the device more reliable.
I noticed that occasionally the mouse would only pick up some of the changed settings. The official configurator waits 10 ms between each message and 20 ms before the save. Adding these here seems to have made the writes more reliable.
> steelseries: sleep between messages

- data/gnome/logitech-g502.svg
In Piper utility, leds configuration is inverted for g502 proteus spectrum
> data/gnome: G502: fix leds position

- data/devices/logitech-g302.device
This short-lived rgb-less edition of the G303 was a bit sad and left out. 
Simply adding its usb ID makes it work.
Thanks a lot for this project!
> Add Logitech G302 device

- circle.yml
- src/hidpp20.c
- src/libratbag-data.c
- tools/check_scan_build.py
https://bugs.llvm.org/show_bug.cgi?id=3888
clang analyzer doesn't know how to handle ```__attribute__(cleanup())```.
There are only 2 warnings raised because the analyzer only look at the current compilation unit for checking the malloc call. So only those 2 are detected by clang and then marked as memory leak.
This also means our current continuous integration doesn't check for memory leaks.
> remove clang analyzer false positive warnings

- src/driver-hidpp20.c
We used to support them, but they are kind of crashing. Kind of fixing them then.
> HID++ 2.0: Support non gaming mice again

- src/driver-gskill.c
- src/driver-test.c
- src/liblur.c
../src/liblur.c:46:3: warning: 'd' may be used uninitialized in this function [-Wmaybe-uninitialized]
hidpp10_device_destroy(*hidpp10_device);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/liblur.c:198:59: note: 'd' was declared here
_cleanup_hidpp10_device_destroy_ struct hidpp10_device *d;
And similar messages
> Initialize a few _cleanup_ pointers to NULL

- data/devices/logitech-g102-g203.device
- data/gnome/logitech-g102-g203.svg
- meson.build
Just a quick change to add support for the G102 and G203 mice.
These mice are functionally identical and share a device ID, they only differ in marketing materials and which countries sell each mouse.
> Include Logitech G102/G203 device files

- tools/merge_ratbagd.py
Fix UTF-8 encoding on merge_ratbagd.py. Tested on Python 3.6.5, Ubuntu 18.04. See #493 for details.
> Fix UTF-8 encoding on merge_ratbagd.py, per #493

- meson.build
- meson_options.txt
This is more meson-like, the "enable-foo" is a autotools leftover.
> meson: change to use "-Dtests=true" instead of "enable-tests"

- meson.build
Needed for build_by_default
The logs of configuring current meson warns about this:
```
The Meson build system
Version: 0.47.1
Source dir: /home/phomes/libratbag
Build dir: /home/phomes/libratbag/builddir
Build type: native build
Project name: libratbag
Project version: 0.9.902
Native C compiler: cc (gcc 8.1.1 "cc (GCC) 8.1.1 20180712 (Red Hat 8.1.1-5)")
Native C++ compiler: c++ (gcc 8.1.1 "c++ (GCC) 8.1.1 20180712 (Red Hat 8.1.1-5)")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Program git found: YES (/usr/bin/git)
Found pkg-config: /usr/bin/pkg-config (1.4.2)
Native dependency libudev found: YES 238
Native dependency libevdev found: YES 1.5.9
Native dependency libsystemd found: YES 238
Native dependency systemd found: YES 238
Native dependency glib-2.0 found: YES 2.56.1 …
```
> meson: bump min version to 0.40.0

- src/driver-hidpp10.c
- src/libratbag.c
HID++1.0 devices store the profile name. Update the name used by libratbag.
The name will be used in the output from ratbagctl. Piper does not yet make used of the name.
> Hidpp10 profile name

- data/gnome/check-svg.py
- data/gnome/logitech-g9.svg
When looking into why setting macros are not working on the G9 (HID++1-0) I noticed that the G9 svg was missing the wheel left/right buttons, and that thus some buttons were also numbered wrong.
Adds wheel left/right clicks and adjusts button numbering.
(Button5 seems to be configurable in the profile, but no such button
exists on the mouse)
> update logitech G9 SVG

- src/libratbag-data.c
- tools/lur-command.c
Those are required to compile libratbag under musl libc systems which are stricter
Error log
```
FAILED: lur-command@exe/tools_lur-command.c.o 
x86_64-linux-musl-gcc -Ilur-command@exe -I. -I.. -I../src -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -std=gnu99 -Wno-unused-parameter -fvisibility=hidden -Wmissing-prototypes -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -O2 -pipe -mtune=generic -lelogind -I/usr/x86_64-linux-musl/usr/include -MD -MQ 'lur-command@exe/tools_lur-command.c.o' -MF 'lur-command@exe/tools_lur-command.c.o.d' -o 'lur-command@exe/tools_lur-command.c.o' -c ../tools/lur-command.c
../tools/lur-command.c: In function ‘find_receiver’:
../tools/lur-command.c:145:12: error: ‘PATH_MAX’ undeclared (first use in this function); did you mean ‘INT8_MAX’?
char path[PATH_MAX] = …
```
> src/libratbag-data.c tools/lur-command.c: add missing limits.h includes

- meson.build
- meson_options.txt
Allows systems that provide libelogind (which provides a portion of
libsystemd that libratbag uses) to also compile without having to patch
out the rest of the build to remove the full systemd dependency.
This commit:
- Adds a systemd swith on meson_options.txt, a boolean set to true as
default to keep expected behaivour
- Adds a check on meson.build for the systemd switch and adds
dep_systemd
- Guards sections meant to generate systemd service units under the
systemd switch
> meson.build meson_options.txt: Add systemd switch

- tools/ratbagd.py
Not sure why this is happening exactly, but it's better to handle this case
without an immdiate exception.
Fixes https://github.com/libratbag/piper/issues/228
> tools: make ratbagd a bit more robust regarding None object path lists

- tools/toolbox.py
Popped up in https://github.com/libratbag/libratbag/pull/515
> tools: make the dbus directory before trying to copy to it

- ratbagd/ratbagd-button.c
In the review of #516 I requested error logging when we converted an invalid special action to an unknown. That turned out to be a mistake.  Clients e.g. ratbagctl ask for all properties, so this getter function gets called often even if the button is not a special action. I only thought that we would call the getter of the actual button type, and that each conversion from invalid to unknown would thus be due to an internal confusion of the type. I was wrong.
We do not want to send the value for an invalid special action as
that is negative 1. Converting to unknown is good enough here so
let's just remove the error logging and convert in silence.
> ratbagd: do not warn when converting invalid special action

- ratbagd/ratbagd-button.c
- ratbagd/ratbagd-device.c
- ratbagd/ratbagd-led.c
- ratbagd/ratbagd-profile.c
- ratbagd/ratbagd.c
- ratbagd/ratbagd.h
- tools/ratbagd.py
First patch makes sure we don't crash out if we ever get None from an array property - which can happen when an error occurs.
The second patch wraps all (well, most) the `sd_bus` calls that are pure scaffolding into a macro that logs an error if they fail. This way we at least get notified when a basic "open message" or "append value" call fails, causing a property to end up being None.
> Make ratbagd and ratbagd.py more robust for errors

- src/driver-hidpp10.c
- src/driver-hidpp20.c
- src/driver-steelseries.c
- src/libratbag-hidraw.c
- src/libratbag-hidraw.h
- src/libratbag-private.h
This is a bit of work in progress, but is still usable as is. The motivation for pushing this now is the plans for changing from udev for flatpak support in ratbagd which would require changes in the same code.
This PR will add support in libratbag for those devices that receive reports on one endpoint but send the response on another. This is done by mice from both steelseries and cooler master. In this PR we added the functionality needed in libratbag itself and starts to make use of it from the steelseries driver.
More work is needed to read a full profile from the steelseries mice, but @FFY00 has already understood a good part of the protocol needed. I would love to see followup patches with additional data read, and more testing of device/firmware differences.
> Read input reports from different endpoint

- meson.build
- meson_options.txt
#510 adds support for building without systemd itself, but still probes for libsystemd. However, elogind by default doesn't install libsystemd.pc but only libelogind.pc.
> build: support building with elogind

- ratbagd/ratbagd.c
sd-bus returns EEXISTS which is "File exists" and way too confusing. Let's
print out a decent error message for that case.
Relater #535
> ratbagd: provide a decent error message when the bus name is taken

- meson.build
- meson_options.txt
no, not coverity fixes, but really "fix coverity". It doesn't like gcc7 and spews things like undefined type _Float128 by the millions (you can never have enough of those errors, I guess).
So let's give libratbag a special "be nice to coverity" option and let meson define all the types coverity is really unhappy about.
> Fix coverity

- data/devices/logitech-gpowerplay-wireless.device
Tested with a Logitech G903, should also work with a Logitech G703.
May also work with other Logitech mice that work with a G900 receiver.
> Add Logitech G PowerPlay wireless configuration

- tools/ratbagc.py.in
- tools/ratbagd.py
It's already encoded as part of the enum, no need to have it again for the
value
> tools: remove the unnecessary prefix from the error code enum

- src/driver-hidpp10.c
If we can successfully read a profile but hidpp10_get_current_profile() fails
we end up with one profile, but not set to active. Fix this by always forcing
the single profile to be active.
Fixes #526
> driver-hidpp10: force the single profile to be active

- circle.yml
Some change in F29 breaks the CI runs, so lets switch back to what we had
before so we can merge patches.
> circle CI: switch fedora latest to fedora 28

- src/driver-roccat.c
Turns out this driver never got updated for the 'new' DPI list provided by
libratbag and thus broke with bacdab259653512e06631075216f090eadc435dc when we
enforced that DPI list.
Set a fixed DPI list based on the hardcoded values we use elsewhere in this
driver.
> roccat: set the dpi list

- data/gnome/check-svg.py
- data/gnome/logitech-g502.svg
Fixes https://github.com/libratbag/piper/issues/240
The button was simply mislabeled in the SVG, new test case added for that now.
> Logitech G502 button 10 fix

- ratbagd/ratbagd.c
- ratbagd/ratbagd.h
ratbagd is not something that needs stay around forever just because we
configured a mouse once. We have DBus activation and we don't store anything
anyway, so we might as well exit after a period of inactivity (20 min).
There's a slight race condition where if something comes in at exactly the
20min mark, we may shut down anyway and the messages get lost. This is too
narrow to worry about.
> ratbagd: set up a simple exit-on-idle

- ratbagd/ratbagd-device.c
- ratbagd/ratbagd.c
- ratbagd/ratbagd.h
Schedule the actual operation as a callback to handle at the end of the event
loop and return success. The Resync signal will handle the rest.
> ratbagd: make Commit() truly asynchronous

- ratbagd/ratbagd-button.c
- ratbagd/ratbagd-device.c
- ratbagd/ratbagd-led.c
- ratbagd/ratbagd-profile.c
- ratbagd/ratbagd-resolution.c
- ratbagd/ratbagd.h
Fixes #528
I can see the signals float past on dbus-monitor, but piper doesn't seem to update itself correctly (yet). I think this is an issue with piper rather than ratbagd though.
> ratbagd: update all properties before sending out Resync

- meson.build
When building the package in Archlinux I got the following:
```
DEPRECATION: Project targetting '>= 0.40.0' but tried to use feature deprecated since '0.48.0': python3 module
<snip>
WARNING: Deprecated features used:
* 0.48.0: {'python3 module'}
```
``import(python3)`` was [depreciated in 0.48](https://github.com/mesonbuild/meson/blob/master/docs/markdown/Release-notes-for-0.48.0.md#python3-module-is-deprecated).
> meson: conditional check to avoid use of depricated features after Meson v0.48.0

- tools/ratbagc.py.in
- tools/ratbagctl.in
- tools/ratbagd.py
ratbagd now implements commit as normal always-successful call with a
potential Resync signal later if something failed on the device.
PR just so I can have an extra pair of eyes on the other changes here, thanks!
> tools: sync ratbagd.py from Piper - drop async commit

- src/driver-hidpp20.c
A non-zero value for the remapped field means the button is mapped to that
button.
"diverted" means to decouple it from normal HID reports and report it via
HID++ only. In our case here, we "map" it, which is different.
Fixes `button set`/`button get` mismatch listed in #587
> hidpp20: if the button is remapped, use that

- tools/shared.c
This fixes a problem in which running `ratbag-command` with the path to a device node symlink (e.g. `/dev/logi-g502 -> /dev/input/event4`), such as one created by a udev rule, would not work correctly, due to the code failing to resolve the symlink prior to checking for the presence of the `"/dev/input/event"` prefix.
This resulted in nonsensical error messages (shown below) and the curious inability to run `ratbag-command` successfully with anything but the actual raw path to the device node itself (e.g. `/dev/input/event4` would work fine, but `/dev/logi-g502` would not, despite both being valid ways of getting to the same device node).
Error: Can't open '/dev/logi-g502': Success
Error: Device '/dev/logi-g502' is not supported
Note that this same problem also prevented the usage of …
> tools: canonicalize path first in udev_device_from_path

- src/driver-hidpp20.c
As mentioned in the code:
We revert to HW control of the LEDs.
This effectively disable the capability of changing the DPI/profile LEDs, but this allows to make them work with the internal DPI/profile switches.
The net result is:
- DPI/profiles can't be controlled (but who wants this?)
- The logo can properly controlled
Related: #471 
Cc: @dslul
> hidpp20: non-rgb leds: switch back to HW control once configured

- data/gnome/logitech-g-pro.svg
This fixes two issues, both visible in #607:
1. Ensure that Piper renders the device
2. Fix the vertical spacing between two leader lines.
> Fix the Logitech G Pro GNOME SVG

- tools/toolbox.py
toolbox.py:86: DeprecationWarning: time.clock has been deprecated in Python
3.3 and will be removed from Python 3.8: use time.perf_counter or
time.process_time instead
> tools: switch time.clock() to time.perf_counter()

- circle.yml
Scan-build is at the point where it gives us too many false positives to be
reliable and they're not easily fixable other than sprinkling
"ignore_clang_sa_mem_leak" comments all over the source.
This caused us to drop F29 from the CI earlier, see 1225f421c0a50083, but
really we just shouldn't use something that's so unreliable as part of our CI.
The main issue continues to be the use of __attribute__((cleanup)) but others
give us false positives too.
> circleci: drop scan-build from the jobs to run

- doc/dbus.rst
- ratbagd/ratbagd-device.c
- tools/ratbagc.py.in
- tools/ratbagd.py
This is prep work for libratbag 1.0.
These APIs are now legacy, we assume that we're running sandboxed because that's the future. So let's drop them before we commit to maintain these forever.
> DBus: drop the Svg and GetSvg() APIs

- ratbagd/ratbagd-device.c
We don't install the default SVGs anymore and all the effort for new mice goes
into the gnome theme.
> ratbagd: map the default theme to the gnome theme

- src/libratbag.c
Put a guard into libratbag to not push down resolutions we don't support to the device. This way we don't have to worry about this in every driver.
Fixes #121
> Resolution sanity checks

- ratbagd/ratbagd-profile.c
- ratbagd/ratbagd-test.c
- src/driver-test.c
- src/libratbag-test.h
- src/libratbag-util.h
- tools/ratbagctl.in
- tools/ratbagctl.test.in
cc @YoyPa
Add a hack to strip non-ascii symbols from the profile names. Our API promises that the strings we send are UTF-8 (because otherwise we'd get kicked off DBus anyway) but a latin-1 encoded string can be invalid UTF-8, see #617.
Until we have proper encoding/decoding in place, let's hack around this by just dropping anything non-ascii from the profile name. Ideally we should do this in libratbag, but adding it in libratbag is a few LOC, libratbag would require some significant rework.
Fixes #617
> ASCII-only profile name hack

- ratbagd/ratbagd-device.c
- ratbagd/ratbagd-test.c
- ratbagd/ratbagd.c
- ratbagd/ratbagd.h
Right now:
```
$ ratbagctl list
event3: Logitech MX Anywhere 2S         
event5:   Logitech Gaming Mouse G303      
event6:   Logitech G500s Laser Gaming Mouse
```
This is bad because it encourages users to hardcode the event node in their scripts.  And we don't actually care about the event node anyway. With the patch set from #634:
```
hidraw0: Logitech MX Anywhere 2S         
hidraw2:   Logitech Gaming Mouse G303      
hidraw4:   Logitech G500s Laser Gaming Mouse
````
Which is better but still encourages users to hardcode the event node in their scripts. With this glorious patchset:
```
chinchilla: Logitech MX Anywhere 2S         
hamster:   Logitech Gaming Mouse G303      
woodrat:   Logitech G500s Laser Gaming Mouse
```
Boom! No more hardcoding because it should be fairly obvious …
> Scramble user visible ids for ratbagctl

- src/driver-gskill.c
We still need to read the data of all other profiles. This broke in f26de4bb,
the previous loop only did the is-active modification
cc @Lyude
> gskill: don't break after finding the active index

- tools/ratbagc.py.in
ratbagd uses GObjects and properties so we also make use of notify() a
fair bit. Make sure we don't crash out in ratbagc for that, just add an empty
noop function named notify().
```
File "./build/ratbag-command", line 621, in macro
return RatbagdMacro.from_ratbag(libratbag.ratbag_button_get_macro(self._button))
File "./build/ratbag-command", line 741, in from_ratbag
ratbagd_macro.append(type, value)
File "./build/ratbag-command", line 760, in append
self.notify("keys")
AttributeError: 'RatbagdMacro' object has no attribute 'notify'
```
This is a hack, I think we should review how we're using gobjects and normal objects but for now it fixes the crash at least.
> tools: add a noop notify() function to all our classes

- tools/ratbagctl.in
- tools/ratbagctl.test.in
Because it's less funny than having a screaming gopher but a lot more sensible for the most common use-case. And it's a stable API by virtue of the device itself never changing names, so we don't have to worry about users hardcoding hidraw paths or something.
> Allow for basic name matching in ratbagctl

- doc/dbus.rst
- ratbagd/ratbagd-resolution.c
- tools/ratbagc.py.in
- tools/ratbagctl.in
- tools/ratbagd.py
Instead of a fixed (uu) with an extra capability flag, let's just make this a
variant defined to be a u or a (uu), depending on whether we have a single or
a separate resolution.
In the ratbagd.py bindings we return a tuple for both, but a simple len()
check will tell us which one it is.
> ratbagd: change the Resolution property to a variant

- tools/ratbagctl.in
Since 260711470964c73fcfd24bfdbc6ed74f7e7a5d5f we returned the second parser
to handle everything after the device argument. That parser didn't have the
various options we handled in the original one, causing --keepalive to stop
working. Restore this, we care about everything but --help and --version in
the second parser.
> tools: restore --keepalive functionality

- doc/dbus.rst
- src/libratbag-enums.h
- tools/ratbagd.py
We now ignore monochrome LEDs because we probably can't do much with them anyway, so meh. We can revisit that decision if we need to.
> LED color depth documentation

- doc/dbus.rst
- ratbagd/ratbagd-profile.c
- ratbagd/ratbagd-resolution.c
- ratbagd/ratbagd-test.c
- src/driver-etekcity.c
- src/driver-gskill.c
- src/driver-hidpp10.c
- src/driver-hidpp20.c
- src/driver-logitech-g300.c
- src/driver-logitech-g600.c
- src/driver-roccat.c
- src/driver-steelseries.c
- src/driver-test.c
- src/libratbag-enums.h
- src/libratbag-private.h
- src/libratbag-test.h
- src/libratbag.c
- src/libratbag.h
- test/test-device.c
- tools/ratbagc.py.in
- tools/ratbagctl.in
- tools/ratbagctl.test.in
- tools/ratbagd.py
We don't have mice that can do report rates per resolutions, so let's not
commit to that.
This is a DBus API break but also a break in ratbagd, piper will need to
update to fetch the rate/rates from the profile object now.
It's a ratbagctl break as well, ratbagctl info changes slightly and the
resolution is not required as argument anymore.
Fixes #645
> Move the ReportRate into the profile

- doc/dbus.rst
- ratbagd/ratbagd-resolution.c
No longer needed now that the ReportRate is in the profile
(bf127d4c682a97f0d37331af7d9a7e3757fb909a) and the separate
x/y resolution capability is implied by the Resolution value
(8e9dd6f392502b3c29e11ded416ae1cc83949e08)
> Drop the Resolution.Capabilities field

- doc/dbus.rst
- ratbagd/ratbagd-button.c
- tools/ratbagctl.test.in
- tools/ratbagd.py
Fixes #647 
Instead of different entry points that depend on each other, let's just export one entry point that tells us what we need. IOW we now take an enum value (action type) and a variant, the latter depends on the action type to be set.
Doesn't affect ratbagd at this point, it's all abstracted.
> Rework the button mapping API

- circle.yml
- doc/dbus.rst
- doc/index.rst
- doc/meson.build
This isn't ABI anymore, we now documented all possible values in the docs.
> Drop libratbag-enums.h from the dbus docs

- data/devices/logitech-g-pro.device
adding 046d:c08c to the list of usb devices in
> updating deviceMatch for Logitech G Pro #684

- src/libratbag-private.h
At some point meson #defined NDEBUG depending on the build type, thus
disabling asserts. libratbag relies on those, so let's error out if NDEBUG is
defined.
Related #685
> Error out if NDEBUG is defined

- doc/meson.build
We currently assume the user is using Python 2 as default (over Python 3) and so they renamed the Sphinx Python 3 executable to `sphinx-build{3,-3}`. The default name is `sphinx-build` and is usually kept when using Python 3 as the default Python version. With Python 2 dying in 7 months (https://pythonclock.org/) and Sphinx officially dropping Python 2 (https://github.com/sphinx-doc/sphinx/commit/9412bd76b7f5fdf0adc231ef8130e45bda130164) this seems safe to merge.
> meson: add 'sphinx-build' to sphinx executable name list

- src/driver-steelseries.c
`_cleanup_(freep)` would deallocate the pointer returned by `ratbag_device_data_steelseries_get_dpi_range(device->data)` which resulted in a wrong step value. The step count sent to the device was then wrongly calculated due to this erroneous step value.
What about `dpi_list`? This is still an issue there, right?
>  steelseries: fix bug where we were wrongly dellocating dpi_{range,list} 

- src/driver-hidpp20.c
- src/hidpp20.c
- src/hidpp20.h
Newer mice don't report their battery levels. Instead, they report the voltage read by the SOC. The lghub app does some math with it to figure out the percentage, using some tables shipped with it, but for our purposes I believe having the battery voltage (in millivolts) and the status (charging, wireless charging, charged, discharging...) should suffice.
This is related to [this piper issue](https://github.com/libratbag/piper/issues/222) and the discussion there.
> Add battery voltage reporting for newer mice

- data/devices/logitech-MX-Anywhere2.device
My MX Anywhere 2 has a different PID from the one supplied in the default .device file. This adds the PID to the device file to ensure mice with this PID get detected too.
Fixes #721
> data: add other Bluetooth PID to MX Anywhere 2

- src/hidpp10.c
hidpp10_read_memory will return the HID++ error if the request fails.
right now, the error code from hidpp10_read_memory is transparently
passed through hidpp10_onboard_profiles_read_macro. This is problematic
because hidpp10_onboard_profiles_parse_macro only aborts on rc < 0 and
HID++ error are > 0.
---
Is this the right approach. Do we want `hidpp10_onboard_profiles_read_macro` to keep `hidpp10_read_memory`'s error code? Or should I overwrite `rc` when we see that `hidpp10_read_memory` failed?
> hidpp10: fix segfault for the c531 (and possibly other 27MHz receivers)

- src/hidpp20.c
when we read the memory from the device we already align the offset so
that it matches the end of the sector. for ex, for a 255 sector size the
offset will be set to 255-16.
when we copy the memory (using memcpy) we just copy the bytes that will
finish filling the buffer, ignoring that the offset was aligned. we need
to copy the full 16 bytes, otherwise it will fail when sector_size does
not align with 16.
> hidpp20: fix reading onboard profiles (8100)

- data/devices/logitech-MX-Anywhere2.device
I made a typo in my previous PR; the Vendor ID should have been identical to the other ones. This corrects that error.
> Correct Typo in additional PID

- src/hidpp20.c
currently if any use profile is not valid we fallback to the firmware
profiles. this is quite annoying because the user might have only one
valid profile. this patch will keep valid profiles and only fallback to
firmware profiles on a profile by profile basis.
> hidpp20: fall back to firmware profiles on a profile by profile basis

- meson.build
Python 3.8 no longer links to libpython, resulting in undefined references to
Python API.
But it provides a python3-embed.pc now, so let's try using that first and only
fall back on the normal case if that fails.
See https://github.com/mesonbuild/meson/issues/5629
> Use python3-embed as dependency on Python 3.8

- meson.build
> meson: bump project version to 0.9.906

- meson.build
We don't want to accidentally ignore those.
> meson.build: enable -Werror=format-security

- src/driver-roccat.c
- src/libratbag-hidraw.c
- src/libratbag-hidraw.h
Just a wrapper function, in use by the roccat driver. Eventually the other drivers should switch too.
> Add hidraw helpers for readability

- src/libratbag.c
We're initializing them with incrementing indices, let's make sure the list is
initialized that way too. Makes things more obvious in the log when the first
profile to be queried from the device isn't profile 4.
> Append the created profiles/leds/buttons/resolutions, don't insert

- src/driver-steelseries.c
- src/hidpp-generic.h
- src/hidpp10.c
- src/hidpp20.c
- src/libratbag-util.h
> libratbag-util: move data manipulation functions out of hidpp-generic

- src/driver-hidpp10.c
Because our profile struct can never have an NULL name, let's assume the
empty string equals NULL.
> hidpp10: if the profile name is the empty string, make it NULL

- tools/ratbagctl.test.in
When there's a bug that's triggered by the test suite it's hard to figure out
what exactly crashes. So allow starting ratbagd.devel manually and run the
test suite against that process so we can gdb it.
The steps required for this are a bit insane, so the instructions are listed.
> tools: ratbactl.test: if RATBAGCTL_DEVEL is set, use the existing server

- ratbagd/ratbagd-device.c
- ratbagd/ratbagd-test.c
- ratbagd/ratbagd.c
- ratbagd/ratbagd.h
Because we schedule the `commit` handling as idle callback, we may reset the test device before we ever get to run the callback. Add ref/unrefs to the ratbagd device handling to work around that.
> Fix crasher during the ratbagctl test suite

- meson.build
When building with --buildtype=plain, the build fails with the following
error:
cc1: error: ‘-Wformat-security’ ignored without ‘-Wformat’ [-Werror=format-security]
-Werror=format-security was recently added in 43def1b3a5a by #745
> meson.build: fix builds with --buildtype=plain

- src/hidpp-generic.c
- src/hidpp-generic.h
- src/hidpp10.c
- src/libratbag-hidraw.c
some indentations, some linebreaks in the profile raw data, and dropping the "expected_header" and "expected_error" messages which confused me every time I saw them float past.
> hidpp10: make raw debugging messages a bit easier to read

- tools/ratbagctl.in
Let's not maintain that list manually if we can fetch it from the enums.
> ratbagctl: autogenerate the choices list for the specials and led modes

- circle.yml
- meson.build
- ratbagd/ratbagd-json.c
- ratbagd/ratbagd-json.h
- ratbagd/ratbagd-test.c
- ratbagd/ratbagd.c
- src/libratbag-test.h
- tools/ratbagctl.test.in
Right now, we have a hardcoded test device with "magic" values that the tests just have to know. This makes it hard to expand the tests, because it's not obvious which value can be changed without breaking tests or making things worse.
This PR replaces that test device with a new DBus call to load a test device based on a JSON file. That 
most basic one (1 profile, 1 resolution, etc.) and adds a new devel DBus API to load a JSON file with the data to merge into the test device. This makes the test more flexible and more obvious too - it's clear why we can test for say dpi 1300.
I'm planning to squash the test changes into one commit but for easier reviewing it's separated out.
The JSON parsing doesn't have a lot of error checking and is a bit hacky, but since this is a developer-only …
> Add the ability to load test devices via JSON

- doc/dbus.rst
- meson.build
- ratbagd/ratbagd.c
- ratbagd/ratbagd.h
- tools/ratbagc.py.in
- tools/ratbagctl.in.in
- tools/ratbagctl.test.in
- tools/ratbagd.py
- tools/toolbox.py
Synchronizing piper and libratbag is a pain, especially if one runs from a PPA and the other runs from flatpak. Usually something just blows up and then we get to figure out which package doesn't match.
We haven't done anything about this in the past because the stable DBus API was always just around the corner. Let's give up on that hope and add a specific field with the version so it's easier to force the compatibility. We can remove that in a few decades when we finally finish the API.
> Add a APIVersion field to ratbagd

- data/devices/logitech-g305.device
- meson.build
- src/driver-hidpp20.c
- src/hidpp20.c
- src/hidpp20.h
- src/libratbag-data.c
- src/libratbag-data.h
Reverts libratbag/libratbag#784
Sorry, need to revert. This fails to compile, there's a `;` missing after the enum declaration. which makes me wonder why circleci didn't run on this PR.
And looking at the git log (reviewed the whole diff before and didn't notice): 
```
+enum {
+       HIDPP20_QUIRK_NONE,
+}
+#define HIDPP20_QUIRK_G305     
```
That's fixed in the second patch so I guess that's a rebase gone wrong?
And the test suite now fails with `AssertionError: Quirk must be in ['DeviceIndex']`. Also something that should've been picked up by the CI which for some reason didn't run.
> Revert "add quirk system & full support for the G305"

- data/devices/logitech-MX-Master.device
Added support for the item in question. The device ID for the AMZ version is different from the standard one. Simply adding a new bluetooth device ID in the device match makes the mouse working. I have just updated the Logitech MX Master device file
> added bluetooth device ID in profiles for Logitech MX Master AMZ (amazon)

- data/devices/logitech-MX-Master.device
As seen here: https://github.com/torvalds/linux/blob/master/drivers/hid/hid-logitech-hidpp.c#L3717
This mouse is a warranty replacement, shows up as MX Master in Logitech Options but has MX Master 2S Hardware.
> Add missing MX master PID

- src/driver-hidpp20.c
- src/hidpp20.c
We were getting an invalid effect count so we were trying to read effects with an invalid ID, resulting in HID++ errors. This PR fixes that.
> hidpp20: remove errors when using the 8071 feature

- src/driver-hidpp20.c
When the windows driver puts a device host mode it will mark all 8100
profiles as disabled. If no 8100 profile is enabled no libratbag profile
will get enabled. This patch prevents this by marking the first profile
as enabled if no profile is already enabled.
> hidpp20: fallback to 1st profile when no 8100 profile is active

- meson.build
- src/hidpp.i
```
$> sudo python3
Python 3.7.1 (default, Nov 23 2018, 10:01:49)
[GCC 8.2.1 20181105 (Red Hat 8.2.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import hidpp
>>> f = open('/dev/hidraw1', 'r+b')
>>> base = hidpp.hidpp_device()
>>> hidpp.hidpp_device_init(base, f.fileno())
>>> dev = hidpp.hidpp20_device_new(base, 0xff)
>>> hidpp.hidpp20_feature_get_name(0x8100)
'HIDPP_PAGE_ONBOARD_PROFILES'
>>> hidpp.new_uint8_tp()
<Swig Object of type 'uint8_t *' at 0x7f865198fb70>
>>> feature_index = hidpp.new_uint8_tp()
>>> feature_type = hidpp.new_uint8_tp()
>>> feature_version = hidpp.new_uint8_tp()
>>> hidpp.hidpp_root_get_feature(dev, 0x8100, feature_index, feature_type, feature_version)
0
>>> hidpp.uint8_tp_value(feature_index)
14
```
Signed-off-by: …
> swig: generate python helpers to use hidpp C library

- ratbagd/ratbagd.8
- ratbagd/ratbagd.c
- tools/toolbox.py
TBH `--verbose` is not really that useful. We receive a several of report where the users pasted the log with `--verbose` and 99.9% of the cases that is not helpful, we need `--verbose=raw`. I think it would make sense for `raw` to be the default level when `--verbose` is specified.
> ratbagd: make raw the default verbosity level

- ratbagd/ratbagd.c
When no device is present, starting ratbagd even with --verbose prints exactly
nothing. Let's be more verbose here to give the user an indication that
something's happening. The user wants everything, is probably willing to
accept anything but in the end all we can say is that we have nothing.
Related to #862
> ratbagd: print two verbose messages at startup

- src/libratbag.c
This was copied from libinput and made sense while libratbag was a library -
we want "unhandled" messages to end up somewhere and stderr is the most likely
candidate here.
Now that we always run within ratbagd and it's all effectively inseperable,
just log to stdout for anything below error.
> libratbag: only log to stderr for error messages

- data/devices/receiver-check.py
- meson.build
We don't want any device files that use the receiver itself as a match so
let's test for that. In virtually all cases this means the user must update
the kernel and hope support for that receiver is already present in that
version.
@bentiss, @FFY00 - what are the new receiver IDs again? I've only added `0xc52b` and `0xc532` here.
> data: add a test for unifying receiver IDs

- src/driver-hidpp20.c
- src/hidpp20.c
Fixes: #833 
Fixes: #846 
The second patch is not well tested. But I think it should work. Linux kernel version 5.4 causes serious regression of my system and force me to switch back to an old kernel.
> drivers: fix G305 quirk detection

- src/hidpp20.c
- tools/ratbagc.py.in
- tools/ratbagctl.test.in
- tools/ratbagd.py
Minor ratbagd/ratbagc adjustments:
- Bumped copyright to 2019.
- Fixed typo in profile.capabilities description.
- only ratbagd.py: Removed vim helper line since the file has a proper file extension.
Fix missing capability in ratbagctl.test
hidpp20: set dictionary output to raw
> Minor fixes

- src/libratbag.i
- tools/ratbagc.py.in
- File "./build/ratbag-command", line 2289, in open_ratbagd
r = Ratbagd(1)
TypeError: __init__() takes 1 positional argument but 2 were given
- AttributeError: module 'libratbag' has no attribute
'ratbag_device_get_bus'
- File "./build/ratbag-command", line 267, in model
return "{}:{04x}:{04x}:{d}".format(bus, vid, pid, version)
KeyError: '04x'
- swig/python detected a memory leak of type 'uint32_t *', no destructor
found.
> ratbag-command fixes

- data/devices/logitech-g910.device
- meson.build
Same situation than the G513, 0x8100 is not present.
But heh.
> data: add G910

- data/devices/data-parse-test.py
So I merged #879 without waiting for the CI because it just added a device file but it turns out our test to verify the HID++ index is wrong.
> tests: fix data parse for hidpp index

- tools/ratbagd.py
If access failed, e.g. due to insufficient permissions, don't confuse
the user by reporting an API mismatch.
This is a minimal improvement to target issue #802. As, if access is
restricted to a group, that group is known in Meson, it would even be
possible to report that group in the error message. But, that would
require converting ratbagd.py to a template or finding some other way to
inject that information at build time.
> Give a more specific error message if user cannot reach ratbagd

- README.md
`... a DBus daemon to configure gaming mice.` > `... a DBus daemon to configure input devices, mainly gaming mice`
> docs: adjust description to say we support other devices than mice

- .circleci/config.yml
- .editorconfig
- data/devices/data-parse-test.py
- data/devices/duplicate-check.py
- data/devices/receiver-check.py
- tools/merge_ratbagd.py
- tools/ratbagc.py.in
- tools/ratbagctl.devel.in
- tools/ratbagctl.in.in
- tools/ratbagctl.test.in
- tools/toolbox.py
Removed all `# vim:` lines, EditorConfig is available not just for [vim](https://github.com/editorconfig/editorconfig-vim), but basically any IDE: https://editorconfig.org/#download
> Use EditorConfig instead of vim comments

- src/driver-hidpp20.c
- src/hidpp20.c
- src/hidpp20.h
0x8071 is still missing but as of now we don't have any device that
needs it.
> hidpp20: enable 0x8070 (ColorLedEffects) standalone use

- src/libratbag-private.h
- src/libratbag-test.c
- tools/shared.h
gcc 10 complains about multiple definitions of these when linking.
```
/usr/bin/ld: libhidpp.a(src_hidpp-generic.c.o):/builddir/build/BUILD/libratbag-0.12/x86_64-redhat-linux-gnu/../src/libratbag-private.h:588:
multiple definition of `etekcity_driver';
libutil.a(src_libratbag-util.c.o):/builddir/build/BUILD/libratbag-0.12/x86_64-redhat-linux-gnu/../src/libratbag-private.h:588:
first defined here
```
Special case here is the test_driver struct, without the extern gcc seems to
think it's a new struct with all zeros, causing a segfault when we then try to
strcmp the test driver name.
> Declare a bunch of structs as extern

- src/driver-hidpp20.c
- src/hidpp20.c
- src/hidpp20.h
Now we should be ready for a new release. This fixes the error described in #903 and makes sure we don't overwrite the effects saved in the keyboard if they're not supported.
> Misc fixes for HID++ 2.0 keyboards

- .circleci/config.yml
I noticed that #926 failed (https://app.circleci.com/jobs/github/stephanlachnit/libratbag/286), because `diff` is missing. I checked it and it looks like it went lost in af30fc28cd51534ea5043b18a73ec66a9eee6799, after it was added in f6546b3222dc7e888d5e88c00e55136716eddfab.
> circleci: add diffutils dependency for fedora

- tools/ratbagctl.in.in
For example, with my G513:
Before
```
hooting-chinchilla - Logitech G513 Carbon Tactile
Model: usb:046d:c33c:0
Number of Buttons: 4
Number of Leds: 0
Number of Profiles: 1
Profile 0: (active)
Name: n/a
Report Rate: 0Hz
Resolutions:
Button: 0 is mapped to UNKNOWN
Button: 1 is mapped to UNKNOWN
Button: 2 is mapped to UNKNOWN
Button: 3 is mapped to UNKNOWN
```
After
```
hooting-chinchilla - Logitech G513 Carbon Tactile
Model: usb:046d:c33c:0
Number of Buttons: 4
Number of Leds: 0
Number of Profiles: 1
Profile 0: (active)
Button: 0 is mapped to UNKNOWN
Button: 1 is mapped to UNKNOWN
Button: 2 is mapped to UNKNOWN
Button: 3 is mapped to UNKNOWN
```
> ratbagctl: don't print empty properties

- .circleci/config.yml
The 19.04 repos give us 404s, so let's update to the next version.
> circleci: bump to use ubuntu 19.10

- src/libratbag-data.h
> libratbag-data: add missing header entry

- src/driver-hidpp10.c
- src/driver-hidpp20.c
Should fix #900
I also sneaked in a fix for HID++ 2.0.
> Use macro in favor of the deprecated key button type in HID++ 1.0

- src/hidpp20.c
We now have a routine to identify the supported report types so it is safe to go ahead and use short reports when possible.
> HID++ 2.0 Cleanup

- .github/ISSUE_TEMPLATE/bug_report.md
> github: add device info to bug report template

- meson.build
This code assumes that there is a python3 or python3-embed pkg-config
file on the system, which may or may not be true. On Gentoo for example,
only python-X.Y pkg-config files are available and this will fail to
build.
This makes use of the new py_installation.dependency(embed : true) if
possible, and falls back to trying to find a python that matches the
version of python found by the python3 or python module.
> meson: make finding python more robust

- meson.build
I misread the documentation about the python3 module. The newer python
module puts the language_version in the object returned by
`pymod.find_installation()`, while the python3 module has the same
method in the *module*.
Fixes #985
> meson: Fix python3 version detection with python3 module

- .circleci/config.yml
20.04 is an LTS release, so we should use it, and hopefully we don't need to bump it until 22.04 LTS^^
> ci: bump Ubuntu to 20.04

- tools/ratbagd.py
Same as https://github.com/libratbag/piper/commit/39d6cec5004f95574483b09d4a9ae0682db76cbe from https://github.com/libratbag/piper/pull/549.
Closes #1017.
> remove unused string format to fix flake8

- data/devices/logitech-M720.device
> data: add additional USB-ID for the M720 Thriatlon

- data/devices/logitech-g5-2007.device
- src/hidpp10.c
Before this patch, ratbagd would abort initialization of the device because
no profiles are returned.
Once that was handled more gracefully, ratbagd would fail because it doesn't
read the DpiList from its own config file, as no ProfileType is specified.
Specifying G500 as the closest match.
> Fix enumeration of Logitech G5 (2007)

- src/libratbag-private.h
When compiling on Ubuntu 20.04 with GCC 9.3.0 and glibc 2.31, I get:
In file included from ../src/libratbag-private.h:32,
from ../src/driver-sinowealth.c:24:
../src/libratbag-util.h: In function ‘asprintf_safe’:
../src/libratbag-util.h:154:7: warning: implicit declaration of function ‘vasprintf’; did you mean ‘vsprintf’? [-Wimplicit-function-declaration]
154 |  rc = vasprintf(&result, fmt, args);
|       ^~~~~~~~~
|       vsprintf
This appears to be because <features.h> is being included by another
header before config.h has been included. If _GNU_SOURCE has not been
defined at that point, then the other macros that control whether
vasprintf is declared are not set correctly.
Include config.h right at the top of libratbag-private.h to ensure
that _GNU_SOURCE is defined before any system …
> libratbag-private.h: Ensure that _GNU_SOURCE is defined early enough

- data/devices/logitech-g9x-Original.device
Merged G9x with Call of Duty edition.
Updated with DPI LED
also updated min DPI (200) and increments (50), although I can't confirm if CoD edition is the same.
updated support links
> update and merge logitech g9x

- data/devices/nubwo-x7-spectrum.device
- meson.build
- src/driver-sinowealth-nubwo.c
- src/libratbag-data.c
- src/libratbag-private.h
- src/libratbag.c
Nubwo X7 Spectrum is a sinowealth-based gaming mouse.
The `sinowealth-nubwo` driver included in this commit provides
- LED support (except for color modes that are not available in libratbag)
- DPI and reporting support
The driver doesn't suppoty
- button mapping/macros
fixes #1042
> Add driver for Nubwo X7 Spectrum

- src/driver-sinowealth.c
The glorious mice uses a single profile. To differentiate between
resolutions each one has customizable color. A led on the bottom
of the mouse shows the active resolution color.
Libratbag does not support a per-resolution color.
To allow adjusting these colors the sinowealth driver defines a led
for each resolution. This is a misuse of the model and will cause
problems when the mouse is added to Piper.
This patch removes the per-resolution leds and hardcodes the led
count to one.
> sinowealth: remove per-resolution led

- .circleci/config.yml
Bump to fedora 32 to get updated meson version. This will hopefully fix #1067
> circleci: bump to fedora 32

- ratbagd/ratbagd-json.c
Compilation on clang failed as we would try to jump to the 'out' label and then jump over the initialization of a variable with __attribute__((cleanup)).
We move the initialization up to make sure it happens before the goto.
> ratbagd-json: fix compilation with clang

- meson.build
Bump the required meson version to match the features that we make use of.
We now also make use of the 'copy:' keyword in configure_file that is available in version 0.47.
> meson: bump required meson version

- src/driver-logitech-g600.c
Code implements a possible solution to #598 
Due to the locality of G-shift addresses in the memory of the mouse the G-Shift functions can be accessed via the normal button interface with a minor tweak of extending the count to 41. 20 buttons + 20 G-shift buttons + 1 color register.  
> Note:  The color register is between the two button 20 addresses so the code creates a "Phantom" button 20 which should not be used. 
In order to address this issue of the color address for the g-shift operations the code copies the led color from the profile into the g-shift color address. When pressing the g-shift button you get the same color as if you where not.
> Add support for G-Shift keys on g600

- meson.build
This reverts commit e753db72f98dbd0988cd66baef9d4ca2e4ce04e8.
The new version is too recent for lgtm.com.
See https://lgtm.com/projects/g/libratbag/libratbag/logs/rev/pr-c8dd47f8b4d0c40fc0a27b13e031bbb8e6c76987/lang:cpp/stage:Build%20merge_7b2f50275451a899db1bf70b6eaae9d88ecc56d0
> Revert "meson: bump required meson version"

- src/libratbag-data.c
We have been receiving countless issues and PRs reporting or "fixing"
the device IDs because they think it's wrong. Hopefully this will give
them an hint that is intended behavior. If they look closely at the log,
on a recent enough kernel, they should see their device show up with the
internal ID.
> libratbag-data: log message if the device is a Logitech receivers

- data/devices/logitech-MX-Anywhere-3.device
- meson.build
I've confirmed that the device shows up both when connected using unifying receiver and bluetooth.
> data: add device IDs for Logitech MX Anywhere 3

- data/devices/steelseries-kinzu-v2-pro.device
- meson.build
Appears to be basically the same as the V2 - the differences were
mostly in hardware (upgraded switches & image sensor). I've verified
that the list of DPI settings is correct and matches the Windows
software. Adjusting DPI config in both profiles works correctly.
> data: Add configuration for SteelSeries Kinzu V2 Pro Edition

- data/devices/logitech-g-pro-x-wireless-superlight.device
- meson.build
Support for this receiver, and for the device using the powerplay
receiver, still needs to be added to the kernel driver. For now, you can
used the wired connection to configure the device.
You should also not try to use with the powerplay receiver as the kernel
driver does not support the connection and won't forward any input
events to userspace.
Signed-off-by: Filipe Laíns <lains@riseup.net>
> data: add G Pro X Wireless Superlight

- data/devices/logitech-MX-Vertical.device
Fixes #1132, for my own model of MX Vertical at the least.
> data: add extra USB device ID for MX Vertical

- .circleci/config.yml
See my description of the problem in [1].
Essentially, docker is mishandling the failuire when a syscall is not
available, returning EPERM instead of ENOSYS, and making code misbehave.
The current issue with arch is glibc, which explodes on EPERM, causing
pacman to misbehave.
Once the fix hits CircleCI, we will re-enable.
[1] https://github.com/fwupd/fwupd/issues/2894
Signed-off-by: Filipe Laíns <lains@riseup.net>
> ci: temporarily disable arch

- src/driver-openinput.c
These functions are mandatory[1], fail to probe if they fail.
[1] https://github.com/openinput-fw/openinput-protocol/tree/master/specification/device-protocol#mandatory-functions
Signed-off-by: Filipe Laíns <lains@riseup.net>
> openinput: fail probe if we can't enumerate

- src/driver-sinowealth-nubwo.c
driver-sinowealth-nubwo.c was missing to include "config.h" so
_GNU_SOURCE wasn't defined soon enough.
> sinowealth-nubwo: fix implicit declaration of function ‘vasprintf’

- ratbagd/ratbagd.c
Previously the scheduled task would only have been executed after some
other event woke up the mainloop.
If no such event happens, the task will be delayed significantly.
Fixes #1121
> ratbagd: register task to run as soon as possible

- src/driver-sinowealth.c
Firmware version getting command ID was already there, so why not put it to use.
> sinowealth: print firmware version when probing

- tools/ratbagctl.1
This distinguishes the command variants in the synopsis.
While we're at it, tweak the grammar for the --no-commit
description.
Signed-off-by: Stephen Kitt <steve@sk2.org>
> man: add both variants in ratbagctl.1 synopsis

- src/driver-steelseries.c
Judging by rivalcfg's data for Sensei Raw, Rival 100, Rival (300) and Kinzu v2 (all are version 1 devices in our data), it should have been like that from the beginning.
Confirmed on Rival 100.
> steelseries: fix report rate changing for version 1 devices

- src/driver-sinowealth.c
@phomes and @enkore, sorry for the ping, but since you both own SinoWealth-based mice, I'd be really grateful if you could check this.
NOTE: at least on G-Wolves Hati when poll rate is set to a wrong value, the mouse stops moving. I guess official software may fix this, but I'm not too sure, so proceed with caution.
> sinowealth: implement poll rate changing

- src/driver-sinowealth.c
It was limited to six because Glorious' software exposes only so many of them, but mouse firmware by SinoWealth allows up to eight.
> sinowealth: expose all eight resolution slots

- src/driver-steelseries.c
SteelSeries mice using V1 driver don't support changing breathing LED duration precisely, so it was always locked on 5 seconds. Now we try to match desired duration with factory preset values: 3, 5 and 7 seconds.
> steelseries: improve v1 breathing LED duration configuration

- data/devices/logitech-MX-Anywhere2.device
```bash
$ egrep "Name|Handlers" /proc/bus/input/devices | egrep -B1 'Handlers.*mouse'
N: Name="Logitech MX Anywhere 2"
H: Handlers=sysrq kbd mouse1 event12 leds
$ lsusb
Bus 001 Device 005: ID 046d:c52b Logitech, Inc. Unifying Receiver
```
> data: add additional identifier for MX Anywhere 2

- .github/actions/meson/action.yml
- .github/actions/pkginstall/action.yml
- .github/actions/pkginstall/install-apt.sh
- .github/actions/pkginstall/install-pip.sh
- .github/workflows/main.yml
CircleCI is limiting how many runs we can do, which results in pipelines
randomly failing when we've used up the credits for this month.
Let's add a github workflow instead. Unfortunately github workflows are
a bit of a toy api, no support for YAML anchors or extending other jobs,
so there's a lot of duplication needed to get a job to do something.
The actions added in this patch help a bit to make the jobs easier to
understand (copied from libwacom).
This only runs on Ubuntu right now.
> Add a GitHub Workflow as CI run

- meson.build
Released March 2019 we've already relied on some of its features anyway,
let's get rid of the warnings.
> meson.build: require meson 0.50.0

- src/driver-roccat.c
In hindsight, these should've been obvious.
cc @bentiss
> roccat: name two fields correctly

- src/libratbag-private.h
Noticed this while working adding button changing support to Sinowealth driver.
And also add a TODO to make this function support macro actions. I decided not to implement it right now because I don't think would actually be used anywhere.
> Fix ratbag_button_action_match not matching on type NONE

- src/driver-openinput.c
- src/driver-steelseries.c
- src/libratbag-hidraw.c
- src/libratbag-hidraw.h
Currently, we only have functions that will read and timeout after 1s if
no packets were received. The issue with this is that a lot of times we
may catch unrelated packets, such as mouse or keyboard changes.
To solve this, this patch adds a new set of functions suffixed with
_filter, that will keep reading packets until a valid packet if found.
Users define a filter function and pass it as an argument.
Signed-off-by: Filipe Laíns <lains@riseup.net>
> libratbag-hidraw: add filter to hidraw read

- src/driver-steelseries.c
It probably meant to use the macro directly, not `sizeof` of it (which
made it be 4 instead of 64).
Found by clang-tidy. I'm not sure how it worked before considering this, so somebody with a V2 mouse should test this first.
> steelseries: fix length of LED cycle output report being incorrect

- src/driver-steelseries.c
Noticed it was writing report rate even though I didn't change it.
> steelseries: only write report rate if it's dirty

- src/driver-roccat-kone-emp.c
No obvious reason why we need to include that header and it appears to
be glibc-specific. Let's use stdint.h instead (which is already
included).
cc @LittleWhite-tb, @lonjil
Reported in https://github.com/libratbag/libratbag/issues/1253#issuecomment-1038311104
> roccat: remove an unnecessary #include

- src/driver-etekcity.c
- src/driver-roccat-kone-pure.c
- src/driver-roccat.c
- src/driver-test.c
- src/libratbag-private.h
- src/libratbag.c
This basically puts now removed `ratbag_old_write_profile` in every driver that has not yet migrated to the profile-oriented API. The only other change is that now `etekcity` driver only writes profile once. While is might in theory be breaking, I think it's safe to assume it wont as I don't think official software destroys EEPROM of the mouse by repetitive overwriting like it did before this change.
> Remove old driver methods

- src/driver-sinowealth.c
- Make it easier to add new devices by putting devices data into a struct, instead of working with the values manually. This way a person that doesn't understand coding can easily add new data (though they would have to be familiar with building process).
- Automatically detect sensor type, and if the sensor type was recognized, set corresponding maximum DPI.
- Add support for Marvo Scorpion G961, which has shorter configuration data. Though to use it, a device file for ratbagd would have to be created manually, as another mice with the same VID:PID has been reported not to work (Ant Esports GM500). Incidentally it also has shorter configuration data.
- Minor quality of life improvements.
> SinoWealth driver improvemnts

- src/driver-sinowealth.c
Hot-fix.
I did not notice that the logic was inverted when I replaced `strncmp` with `strneq`, and I didn't test it, oops.
I guess that's exactly the reason why `strneq` is more safe. :D
> sinowealth: fix all devices being detected as `generic device`

- src/hidpp20.c
a pristine mouse will often come with competly clean memory and there will be no
active profile set, the result is that mouse cannot be configured by libratbag
at all.
> set first profile as active if no active profile found

- data/devices/logitech-MX-Anywhere3B.device
This variant stands for Logitech MX Anywhere 3 for Business.
Signed-off-by: Sami Olmari <sami@olmari.fi>
> Add device-file for Logitech MX Anywhere 3B

- test/receiver-check.py
Listed here: https://pwr-solaar.github.io/Solaar/devices.html
> test: add the Bolt receiver C548 to the receiver list

- src/libratbag-data.c
This can happen when a device has not properly initialized and this
fields have not been set.
> libratbag-data: fix possible NULL dereferences

- tools/hidpp10-dump-page.c
- tools/hidpp20-dump-page.c
- tools/hidpp20-reset.c
hidpp files were using the error function from error.h header file.
Unfortunately not every libc comes with this particular header file, so
with this patch we won't be requiring to be rely on error function and
use fprintf function.
Thanks to developer Yaroslav Chvanov <staticssleever668> for the
original suggestion
Closes: https://github.com/libratbag/libratbag/issues/1253
Signed-off-by: listout <listout@protonmail.com>
> Use fprintf instead of error

- data/devices/glorious-model-d.device
- data/devices/glorious-model-o.device
- data/devices/sinowealth-0027.device
- data/devices/sinowealth-1007.device
- meson.build
- src/driver-sinowealth.c
- src/driver-sinowealth.h
- src/libratbag-data.c
- src/libratbag-data.h
This moves device data out of the driver into device files. However, a
_single_ device file contains data for _several mice_ at the same time.
The reason for this is that different mice by SinoWealth may use the
same VID:PID pair. This is unfortunate, as we only allow a single
device file a given VID:PID pair.
@whot, what do you think of such a way? I've looked into making it possible to split it further so that each device has it's own device file by allowing several devices with the same VID:PID pair, but it turned out to be quite complex. Doing it like so on contrary was pretty easy.
Unrelated: also move `sinowealth_led_format` enum into a header file and rename
its constants to fit in outside of the driver.
> sinowealth: move device-specific data out of the driver

- data/devices/logitech-g502-x.device
Just received my G502 X and saw it is not yet supported. This trivial change made ratbagd recognize it. Thus pull request addresses the "basic" version of the G502 X connected via USB.
> Add Support for G502 X over USB

- data/devices/asus-rog-chakram-x.device
- data/devices/asus-rog-gladius2-origin-pink.device
- data/devices/asus-rog-gladius2-origin.device
- data/devices/asus-rog-gladius2.device
- data/devices/asus-rog-pugio.device
- data/devices/asus-rog-spatha-x.device
- data/devices/device.example
- src/asus.c
- src/asus.h
- src/driver-asus.c
- src/libratbag-data.c
- src/libratbag-data.h
Some mice uses button order which differs from the default one. So storing button indices won't work for them. I can't rely on the hardcoded buttons table. I have changed ButtonMapping to store the actual button codes in the order that they appear in the packet. So I can get the current bindings and rebind any button.
I also added extra buttons for Spatha X mouse and it's device file. We did some research and tests with device owner in this issue - https://github.com/kyokenn/rogdrv/issues/50.
> ASUS: reworked ButtonMapping config property and added Spatha X mouse

- data/devices/asus-rog-pugio.device
- src/driver-asus.c
I forgot that some mice have zero byte elements in the bindings array. So those elements should be skipped while searching for the button code. It also fixes button bindings info for the Pugio mouse.
> asus: allow empty cells in bindings table and fix pugio button bindings

- src/asus.c
- src/asus.h
- src/driver-asus.c
- src/libratbag-data.c
To fix a compiler warning:
```
[60/72] Compiling C object libratbag.a.p/src_libratbag-data.c.o
In file included from ../src/libratbag-data.c:33:
../src/asus.h:138:27: warning: ‘ASUS_BUTTON_MAPPING’ defined but not used [-Wunused-variable]
138 | static struct asus_button ASUS_BUTTON_MAPPING[] = {
|                           ^~~~~~~~~~~~~~~~~~~
```
> Minor ASUS driver refactoring

- ratbagd/ratbagd-button.c
- src/libratbag.c
- tools/ratbagc.py.in
- tools/ratbagctl.in.in
- tools/ratbagd.py
ASUS devices doesn't support macros, but they support simple keyboard actions. It's already implemented in ASUS driver but libratbag keyboard actions internal implementation is missing. I have implemented keyboard actions in internal API, DBus methods and ratbag-command. I already patched Piper and tested button binding with it, so I'm ready to open PR for the Piper too.
> implement key bindings feature

- src/driver-sinowealth.c
Another portion of improvements:
- Some code quality improvements.
- Support for LMB, RMB and MMB actions in macros.
- Complete support for the second profile if a preproccessor macro is set (subject for removal because of lack of usefulness, kept for archival reasons and to prevent questions like "why is there a set_active_profile() even though there is only one profile?").
> A bunch of SinoWealth driver improvements

- data/devices/logitech-g102-g203.device
New additional usb id for Logitech G102: usb:046d:c09d
> New additional usb id for Logitech G102

- src/driver-hidpp10.c
- src/hidpp10.c
This showed up while working on #1244.
> driver-hidpp10: fix integer overflow when profile count is unset

- data/devices/logitech-g-pro-keyboard.device
Device file for `Logitech G Pro` and `Logitech G Pro X` keyboards
Known issues:
- not possible to change LED color of Caps lock indicator, Scroll lock indicator and Game Mode button.
> data: add device Logitech G Pro (X) keyboard

- data/devices/steelseries-rival-650-wireless.device
- src/driver-steelseries.c
I got the protocol binary implementation entirely from [flozz/rivalcfg](https://github.com/flozz/rivalcfg), and even [their implementation](https://github.com/flozz/rivalcfg/blob/master/rivalcfg/devices/rival650.py) is relatively lacking in expected features like loading settings from the device and LED control, but I went ahead and added what was necessary for me to at least get the polling rate and DPI changes working for me.
**Implemented**
**Possible, but left out**
**Missing abstractions in libratbag, but possible**
**Unknown protocol**
These `PROTOCOL4` patterns should also work with minimal difference for the [`rival3` wireless](https://github.com/flozz/rivalcfg/blob/master/rivalcfg/devices/rival3_wireless.py) as well, but I did not include a `.device` for it as I lack the hardware …
> steelseries: Add "support" for Rival 650 Wireless

- src/driver-etekcity.c
- src/driver-logitech-g300.c
- src/driver-logitech-g600.c
- src/driver-roccat-kone-emp.c
- src/driver-roccat-kone-pure.c
- src/driver-roccat.c
- src/driver-steelseries.c
Otherwise it would be impossible to set one key button actions through Piper, which tries to use key actions instead of macros if the driver says it supports them.
They should actually be easily implementable in most of these drivers, as most of them support macros with only a single key. However, I'd rather not blindly write code I can't test.
> Don't enable key-type button actions in drivers that don't suport them

- src/driver-gskill.c
Regression since 5548da21d335d525955b7b7337fdb836685d89fc.
However I'm almost 100% sure this displays incorrect mouse buttons.
> gskill: add back button type button actions

- dbus/org.freedesktop.ratbag1.service.in
- meson.build
- ratbagd/ratbagd.service.in
Ratbagd requires to be run by root. It should thus live in the system binary directory.
Downstream patch from OpenSUSE, thank you @theMarix!
> build: install ratbagd into sbindir

- src/libratbag-data.c
- src/libratbag-private.h
- src/libratbag-util.h
- src/libratbag.c
- src/libratbag.h
This fixes the following warning:
```
[10/73] Compiling C object libratbag.a.p/src_driver-hidpp10.c.o
../src/driver-hidpp10.c: In function ‘hidpp10drv_write_button’:
../src/driver-hidpp10.c:280:55: warning: passing argument 1 of ‘ratbag_action_keycode_from_macro’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
280 |                 rc = ratbag_action_keycode_from_macro(action, &key, &modifiers);
|                                                       ^~~~~~
In file included from ../src/driver-hidpp10.c:48:
../src/libratbag-private.h:470:63: note: expected ‘struct ratbag_button_action *’ but argument is of type ‘const struct ratbag_button_action *’
470 | ratbag_action_keycode_from_macro(struct ratbag_button_action *action,
| …
```
> libratbag: use const pointers where possible and makes sense

- meson.build
Initially I made them so that you can run them separately to see their output, however, this can be done with meson out of the box. E.g., replace:
`ninja -C builddir python-black-check`
with
`meson test -v -C build python-black-check`.
> build: remove redundant build targets for tests

- data/devices/asus-rog-chakram-x.device
- src/asus.c
- src/asus.h
- src/driver-asus.c
Fixes https://github.com/libratbag/libratbag/issues/1413
Every ASUS mouse have multiple interfaces for mouse, keyboard, configuration and other stuff. There was some error messages because libratbag tried to initialize on the wrong interfaces of the mouse. It tries every interface and fails on the wrong one with error message. This PR fixes it and I have tested this part.
> asus: check for hid report and fix chakram x

- data/devices/logitech-g915-tkl.device
Seems like may have diverged accidentally from G915 in https://github.com/libratbag/libratbag/commit/4f36371af3eb43a012feb52eb9a1908ed0b2ac76#diff-1084927271ae24bc399f4cb5ceb16a4735c4b96e7c46462056cef9740a22d724
Feel free to close out if change was intentional.
> Update logitech-g915-tkl.device to DeviceType=keyboard

- src/driver-sinowealth-nubwo.c
- src/liblur.c
Some basic clang-analyze fixes. There are some harder ones not fixed, you can see them yourself by launching the `scan-build` compilation target (requires clang installed).
> Refactor clang analyze

- tools/ratbagctl.body.py.in
I think we're better off ignoring the warning here (instead of repeating the same argument like 10 times).
Fixes tests failing because UP032 was extended in Ruff (and this has happened before). Pinning Ruff is probably a good idea. (Fixes #1515.)
> fix: ignore a Ruff f-string formatting warning (UP032)

- data/devices/logitech-g413.device
I visited a friend with a G413 (basically a G513 without RGB), and checked the USB-ID. I can't tell you if it works, so I don't know if this should even be merged, just wanted to note it.
> data: add support for Logitech G413 keyboard

- src/driver-sinowealth.c
- src/driver-steelseries.c
- src/hidpp20.c
- src/libratbag-data.c
- src/libratbag-hidraw.c
- src/libratbag-hidraw.h
- src/libratbag-private.h
- src/libratbag-util.c
- src/libratbag-util.h
- src/libratbag.c
..or that's what the branch name says. I've had this tucked up in some branch for a long while.
> Refactor: fix some clang-tidy warnings

- data/devices/logitech-MX-Master-3S-for-Business.device
There is no technical difference between this mouse and the Logitech MX Master 3S.   However, it still gets its own device id and unique name for no apparent reason.
> This device operates exactly like the MX 3S

- test/receiver-check.py
Fixes the receiver test not working basically ever. Fixes #1558.
> test: format receiver IDs as hex numbers

- data/devices/asus-rog-keris-wireless-aimpoint.device
This has been tested on Arch Linux with my personal mouse, the corresponding Piper PR has also been submitted.
> asus: Add Support for ROG Keris Wireless Aimpoint

- data/devices/logitech-MX-Anywhere-3S.device
I add device file for logitech mx anywhere 3s (it's silent version of mx anywhere 3). Tested it on arch linux. Not sure why anywhere3.device contains usb filter, it works fine without it.
> data: add Logitech MX Anywhere 3S

- meson.build
- tools/ratbagctl.body.py.in
- tools/ratbagctl.devel.py.in
- tools/ratbagctl.test.py.in
- tools/toolbox.py
Random fixes for bugs I encountered during the driver development.
The ratbagctl test is always skipped on github actions because it needs to run as root but with python 3.12 the imp module was removed so it always fails even before it can be skipped due to import error.
> Fixes for ratbagctl test

- data/devices/asus-rog-harpe-wireless.device
Adds rog harpe ace wireless. For now it only works plugged in on USB mode. I will update if I can get it to work with the OMNI receiver.
> add rog harpe ace wireless
